### ISSUE TITLE
How to add headers in the client side? 

### ISSUE THREAD

**Issue by ivanjunckes** [eclipse/microprofile-rest-client#104]
I would like to be able to pass the "Authorization" header in the client side? How can I do that?

**Comment by andymc12** [comment]
Hi @ivanjunckes - thanks for opening this issue.  There isn't a defined way to specify Authorization credentials in MP Rest Client today, but there are a few ways to make it work.

You could create the credentials yourself and pass it in as a `@HeaderParam` like this:
```
private String createBasicAuthHeaderValue(String username, String password) {
    return Base64.getEncoder().encodeToString((username + ":" + password).getBytes(‌"UTF‌​-8"​));
}

...

@Path("/somepath")
public interface MyRestClient {

    @GET
    @Path("/requiringAuthHeader")
    Response getSomeData(@HeaderParam("Authorization") String authHeaderValue, ...);
}

...

Response r = myRestClient.getSomeData( createBasicAuthHeaderValue("user1", "password1"), ... );

```

You could also tuck the authorization `@HeaderParam` into a bean parameter if that makes more sense - for an example, you can view the TCK code here:
https://github.com/eclipse/microprofile-rest-client/blob/master/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/interfaces/MyBean.java
and
https://github.com/eclipse/microprofile-rest-client/blob/master/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/interfaces/InterfaceUsingBeanParam.java

If you want to propagate an existing `Authorization` header (i.e. you are already in a JAX-RS resource method and you want to pass the auth credentials of the calling client to an outbound call of another service), then you might be able to use the propagating filter example that I posted at:
https://github.com/andymc12/HttpHeaderPropagation/blob/master/src/io/openliberty/propagate/HeaderPropagationFilter.java
You would need to ensure that you register an instance of this class to both your JAX-RS application and the MP Rest Client.

Hope this helps, Andy

**Comment by OndrejM** [comment]
Hi, @ivanjunckes, is this issue about adding general headers to the REST request? I believe that @andymc12 explained how to do that and it seems pretty straightforward to me.

Or is this about propagating the Authorization header from a server resource to client REST requests? This would be nice to have, but then we should raise a new issue and close this one.

**Comment by ivanjunckes** [comment]
Hey guys, sorry for not following up on this. I just forgot to come back to the ticket.
I ended up resolving this issue using ClientRequestFilter to add the authorization header in the request.

What I needed was not really about propagation but for adding headers.
