### ISSUE TITLE
reactive compatibility

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-rest-client#105]
Over in https://github.com/eclipse/microprofile-reactive there is work being done to support
a microprofile reactive streams spec. 

See https://developer.lightbend.com/blog/2018-02-06-reactive-streams-jakartaee/index.html for
some background.

I am aware of https://blogs.oracle.com/pavelbucek/jax-rs-21-reactive-client-api and also #10 but in order to get the benefits of reactive it helps if all the 'specs' are 'plug-compatible' to enable apps to compose things together functionally, use operators have backpressure handled correctly etc.

This issue is a place to discuss how this spec will fit in with a (microprofile)reactive programming
approach.

**Comment by hutchig** [comment]
@roper ^^^

**Comment by hutchig** [comment]
There is some discussion in the google group:
https://groups.google.com/d/msg/microprofile/18SNnnWe4pQ/ej3dQJCyBQAJ

**Comment by hutchig** [comment]
The concrete action here would be to develop a:

https://github.com/eclipse/microprofile-reactive-messaging/blob/master/api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/IncomingConnectorFactory.java
and
https://github.com/eclipse/microprofile-reactive-messaging/blob/master/api/src/main/java/org/eclipse/microprofile/reactive/messaging/spi/OutgoingConnectorFactory.java

That can be used as a `@Connector` in a MicroProfile Reactive Messaging
application.

**Comment by Emily-Jiang** [comment]
We met today but the spec team feels this is implementation related. Close this issue. Please reopen if you think otherwise.
