### ISSUE TITLE
JAX-RS annotation on interface

### ISSUE THREAD

**Issue by Jamsek-m** [eclipse/microprofile-rest-client#106]
Hello,
I am working on an 1.0 implementation where I am using Jersey for Jax-rs implementation and Weld for CDI, but I have encountered a problem:

Jersey does not support JaxRs annotations on interfaces (which is by specification jsr370-2.1 chapter 3.6) if they are not implemented. Therefore when I try to run example I get 
```
org.jboss.weld.exceptions.IllegalArgumentException: WELD-001508: Cannot create an InjectionTarget from 
[EnhancedAnnotatedTypeImpl] public abstract interface @RegisterRestClient @Produces 
@Dependent @Consumes @Path class app.services.RestApi as it is an interface
```

If I override my Application class with `getClasses()` method and put valid resources without RC interface I get it working, however if I do not do that, then automatic scan picks up RC interface as well and I get previously mentioned exception.

Is there any way I can make a workaround for this Jersey limitation?

**Comment by OndrejM** [comment]
It seems that we hit a similar problem with our Payara Micro implementation. We needed to patch Jersey.
Here's the commit in Payara source code: https://github.com/payara/Payara/pull/2800/files#diff-1a0ff1b907622b750405cad68426242dR262 (the fix is in the patched Jersey version 2.27.payara-p5). The patched version of Jersey is here, but it's bit of a mess: https://github.com/payara/Payara_PatchedProjects/pull/161/files

**Comment by OndrejM** [comment]
I guess the other way around would be to avoid automatic scanning, do the scanning yourself and provide Jersey your list of resource classes.

**Comment by derekm** [comment]
Weird. Jersey never had that problem with its native WebResourceFactory.

Another thing we need in JAX-RS/Jersey/MP Rest Client is the ability to
combine BeanParam objects with JAXB objects. Old versions of Jersey used to
support this, but recent version reject dual-use BeanParam/JAXB objects.

**Comment by andymc12** [comment]
Since this seems to be implementation-specific, can we close this issue?  Maybe link it to a Jersey issue?

**Comment by OndrejM** [comment]
Let's close this issue, @andymc12.

@Jamsek-m, feel free to discuss this on the [Jersey mailing list ](https://dev.eclipse.org/mhonarc/lists/jersey-dev/) or on [Payara Forum](http://www.payara.org/forum)
