### ISSUE TITLE
Clarify that @Produces/@Consumes can specify only a single MIME-TYPE

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-rest-client#110]
I've already raised that it's not specified which of `@Produces` and `@Consumes` is used as a MIME-TYPE for request body in #109.

Both JAX-RS annotations allow multiple MIME-TYPEs in the value as an array. But on client side, one of them, which should specify the request body MIME-TYPE, should allow only one MIME-TYPE as a value and it should be specified what happens if there are multiple values.

* On the server, the incoming (consumed) MIME-TYPE is defined by request body content type and the produced MIME-TYPE can be defined by the `Accept` HTTP header. Therefore it makes sense to define multiple values (separated by a comma) for both `@Consumes` and `@Produces` and the container will select which MIME is used
* On the client side (in MP REST Client API), the incoming MIME-TYPE is derived from the response. But there's no way how to specify the outgoing MIME-TYPE in the request if there are more possible MIME-TYPEs so the behavior is unspecified if multiple MIME-TYPEs are specified.

For example, Jersey's client proxy chooses only the first MIME-TYPE specified and ignores others: https://github.com/jersey/jersey/blob/master/ext/proxy-client/src/main/java/org/glassfish/jersey/client/proxy/WebResourceFactory.java#L317

Possible solution is to specify that if multiple MIME-TYPEs are specified for request body, the first one in the list is used.

**Comment by OndrejM** [comment]
Additionally, we can allow that a method has an argument that specifies the outgoing MIME-TYPE dynamically, such as:

```
@Produces(MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON)
public Something postSomething(Something something, @Context MediaType requestBodyMimeType)
```

When called with `service.postSomething(something, MediaType.APPLICATION_JSON)`, the request body will be mapped to JSON.

However, this is probably an edge usecase and should already be supported by passing Entity as an argument to the request method, such as `postSomething(Entity.entity(something, MediaType.APPLICATION_JSON))`, although we should cover it by the TCK (and probably also by the spec doc) if it isn't already.

**Comment by andymc12** [comment]
It sounds like CXF implements this slightly different from Jersey - instead of only using the first MediaType specified in the `@Consumes` annotation for the `Content-Type` header, CXF does a sort (similar to the JAX-RS resource side) in order to find the more specific content types (and avoid wildcards).

In either case, I think it is probably fine if we accept the Rest client is a service-centric view (see issue #113).  The idea then is that the service could consume MediaTypes X, Y, and Z and so it shouldn't matter which one the client selects as it's `Content-Type`.  If the client side wants to use only a specific MediaType (i.e. only send things in JSON), then they could restrict the `@Consumes` to that MediaType.

If nobody objects, I'll plan to add some text to this effect in the same pull request that I am doing for issue #109 - something like:
"If multiple media types are present in the `@Consumes` annotation, then the implementation is free to select one to construct the `Content-Type` header.  If the remote services can consume multiple types, but the client prefers to send only one type, it is advised that only that type is specified in the `@Consumes` annotation on the Rest Client interface."

**Comment by kenfinnigan** [comment]
+1

**Comment by derekm** [comment]
I think @andymc12 has the most correct approach: default to the first most-correct `Content-Type`.

Another sane solution is to specify preferred content type(s) in the `ClientBuilder` (in JAX-RS 2.2) or the `RestClientBuilder` (in MP Rest Client).

In my case, I have completely unified the resource definitions that I use on the client-side AND the server-side. Other people will be doing this, too, and it should be encouraged as a best practice. This means that "they could restrict the `@Consumes` to that MediaType" is a non-option except for those who are violating best practices.

**Comment by derekm** [comment]
PS: if an HTTP operation is, e.g., `GET /organizations/123/customers/456`, then my resources are setup such that the client-side call looks like, `Customer customer = client.root().organizations().organization(123). customers().customer(456).get();`.

On the server-side, I implement the interfaces that allow me to create the above client.

**Comment by derekm** [comment]
If we go down this rabbit hole too far, JAX-RS & MP Rest Client are going to be begging for an `/etc/magic`-like database of mime types & media content fingerprints.

Imagine a resource that takes an `InputStream` but accepts GIFs or JPGs. Without magic `file(1)`-like abilities, something like @OndrejM's reply to himself is needed (`MediaType` method parameter as `@Context`).

The part of me that wants everybody to use the same resource interfaces on both the client- and server-sides wants this line stricken from @andymc12's suggested edit:
> "If the remote services can consume multiple types, but the client prefers to send only one type, it is advised that only that type is specified in the @Consumes annotation on the Rest Client interface."
... and `preferredContentTypes(List<MediaType> mediaTypes)` or similar added to `RestClientBuilder` and friends instead.

If the sentence must remain, then I suggest it be tempered to shame people for copy/pasting code or for making the mistake of setting themselves up to keep two disparate things in sync at a distance (the #1 source for bugs in all projects).

**Comment by derekm** [comment]
I would think when the preferred type doesn't match, it would have to fall back to the default behavior of picking the first complete match.

I also agree about preference order, and I meant to imply the same.

Good discussion! Thanks!

**Comment by derekm** [comment]
I have server & client interfaces that look like this:

```java
/**
 * Accepts answers to questions that map to Standard Data Set attributes.
 *
 * @author Derek Moore <a href="mailto:dmoore@fanthreesixty.com">dmoore@fanthreesixty.com</a>
 */
public interface AnswersResource {

    @GET
    @Consumes({
            MediaType.APPLICATION_JSON,
            MediaType.APPLICATION_XML,
            })
    @Produces({
            MediaType.APPLICATION_JSON,
            MediaType.APPLICATION_XML,
            })
    public List<QuestionAnswer> get(@QueryParam("flowId") UUID flowId);

    /**
     * Post an answer to a Standard Data Set question.
     * @param answer an answer to a Standard Data Set question
     * @return the answer as saved
     */
    @POST
    @Consumes({
            MediaType.APPLICATION_JSON,
            MediaType.APPLICATION_XML,
            })
    @Produces({
            MediaType.APPLICATION_JSON,
            MediaType.APPLICATION_XML,
            })
    public QuestionAnswer post(QuestionAnswer answer);

    /**
     * Form post an answer to a Standard Data Set question.
     * @param flowId the flow the question is in
     * @param orgId the id for the org that the question belongs to
     * @param customerId the customer answering the question
     * @param attributeKey the attribute the question answers
     * @param value the chosen value of the attribute
     * @param values the chosen values of the attribute
     * @return the answer as saved
     */
    @POST
    @Consumes({
            MediaType.APPLICATION_FORM_URLENCODED,
            })
    @Produces({
            MediaType.APPLICATION_JSON,
            MediaType.APPLICATION_XML,
            MediaType.TEXT_HTML,
            })
    public QuestionAnswer post(@NotNull @FormParam("flowId") UUID flowId,
                               @NotNull @FormParam("orgId") UUID orgId,
                               @NotNull @FormParam("customerId") UUID customerId,
                               @NotNull @FormParam("attributeKey") String attributeKey,
                               @FormParam("value") String value,
                               @FormParam("values") List<String> values);

}
```

Notice how I could unify the two `@POST`s iff type `QuestionAnswer` could be a dual-use JAXB & BeanParam object!

Jersey used to allow this, but it rejects the type at runtime if it has both annotations.

MP Rest Client should explicitly support dual-use JAXB/JSON-{P,B} & BeanParam objects, then I could get rid of the second `@POST`!

**Comment by Emily-Jiang** [comment]
It seems that some solution has been provided. Close for now. If this is still an issue, please reopen.
