### ISSUE TITLE
Spec clarification around Interface being client facing or service proxy

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-rest-client#113]
Currently it's ill defined as to whether the Interface should represent the Client or Service perspective.

There are several benefits to Service perspective:

- Reuse of the same interface by the actual service as well as any clients. This was definitely mentioned as an advantage in the early spec days by @johnament 
- Aligned with how JAX-RS endpoints are defined today, making it easier for developers to know how it should look
- It represents the Service end of the contract

I can't think of any particular advantages to the Client perspective, but please chime in if others know of some.

Deciding which perspective we're going to take will have impacts on #109, #110, #111.

**Comment by OndrejM** [comment]
An obvious advantage to the Client perspective is usability, isn't it? I was quite surprised to find out that Jersey's proxy chose the server perspective also for a client, which is to me very confusing. From client view, the proxy produces method body and consumes a request from a server, I don't see why it should be the other way around.

All the above advantages mentioned by @kenfinnigan are basically only one advantage - the same interface with the same anntotations can be used for both client and server side. There's no other real advantage. 

I can see a usecase for having the same interface reused for both server and client, but in real world, the interfaces would be almost always different. Clients would define a lot more methods than the server, depending on business case on the client side. And another point is that in microservices, sharing the same code isn't a good practice so the a client service and a server service should have their own interface.

If you specify a client interface separately, then it's totally confusing having to define `@Consumes` for the request mime type and `@Produces` for the accepted response mime types. Don't you think?

**Comment by kenfinnigan** [comment]
@OndrejM you're over simplifying it to say all the three points I mentioned in favor of the Service perspective are all the same.

The interface we are defining with the spec is a representation of the Service we want to communicate with, making the use of JAX-RS annotations on the interface the same as those on the actual service the most logical.

We're then using a client to execute methods on that interface as if it was a service local to our application, but the fact it isn't local is hidden. If we treat the interface as if it's a client to the service, it almost makes it seem like we have a client -> client -> service type call structure which isn't intuitive at all.

With respect to some of your comments above, I don't see how a client interface would define more methods than the service offers. Wouldn't that mean you're creating some kind of aggregated view of multiple services and make the interface even more confusing? How would you map the interface to an endpoint if it's mapped to multiple services?

Sure sharing implementation code between microservices is typically not advisable, but here we're referring to an interface, not an implementation. It can be beneficial when you're interacting with an external service to have an API dependency on the version of the service you want to communicate with. Most 3rd party services provide API artifacts for you to build against. Whether they then build against those interfaces for their implementations I don't know, but I wouldn't say it never happens as that would result in duplicated code and opportunities for mismatches between them.

**Comment by kenfinnigan** [comment]
One thing I've thought of is that confirming a Service perspective might require renaming `@RESTClient` to something that more clearly indicates it's a view of the service being connected to
