### ISSUE TITLE
Clarification of JAX-RS built-in providers, including JSON-B

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-rest-client#114]
I think it's worth to specify that JSON-B is applied automatically, either to specify it in REST client spec or in the umbrella MP 2.x spec. It should be qualified, something like:

 "Since MP Rest Client 1.1 is part of MP 1.4 and 2.0, the list of built-in providers will be dependent on the underlying JAX-RS implementation. In MP 2.0, MP Rest Client implementations are expected to provide a JSON-B provider. This expectation is optional in MP 1.1."

**Comment by andymc12** [comment]
I went back and re-read the JAX-RS 2.1 spec, and I like the language they used regarding JSON-B:

>11.2.7 Java API for JSON Binding
>
>In a product that supports the Java API for JSON Binding (JSON-B) [19], implementations MUST support entity providers for all Java types supported by JSON-B in combination with the following media types: application/json, text/json as well as any other media types matching */json or */*+json.
>
>Note that if JSON-B and JSON-P are both supported in the same environment, entity providers for JSON-B take precedence over those for JSON-P for all types except JsonValue and its sub-types.


We could adopt similar language to indicate the media types it should be used for, the JSON-P exception, and the notion that if the MP implementation also provides JSON-B, then the JSON-B provider is mandatory.

**Comment by kenfinnigan** [comment]
+1 to wording similar to JAX-RS 2.1 spec
