### ISSUE TITLE
MP-rest client 1.1 compatible with JAX-RS 2.1 ?

### ISSUE THREAD

**Issue by cesarhernandezgt** [eclipse/microprofile-rest-client#127]
The [readme](https://github.com/eclipse/microprofile-rest-client/blob/master/README.adoc) file for microprofile-rest-client stated:

> Rest Client attempts to use JAX-RS 2.0 APIs for consistency and easier re-use.

But when you read the [Arquitecture section](https://github.com/eclipse/microprofile/blob/master/spec/src/main/asciidoc/architecture.asciidoc) from /microprofile github proyect it says:

>MicroProfile 2.x releases are based on Java EE 8. .... Thus, the complete list of functional components for MicroProfile 2.1 includes…​MicroProfile Rest Client 1.1

**Comment by kenfinnigan** [comment]
MicroProfile umbrella release in 2.x has updated to Java EE 8 versions of JAX-RS, ie. JAX-RS 2.1.

However, REST Client currently has not been updated to utilize any specific features from JAX-RS 2.1, which makes it based on and compatible with JAX-RS 2.0

**Comment by cesarhernandezgt** [comment]
Thank you @kenfinnigan for the detailed answer.
