### ISSUE TITLE
TCK - wrong assumption in AsyncMethodTest#testAsyncInvocationInterceptorProvider()

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-rest-client#132]
According to the spec: _"Providers on the outbound client request chain (such as `ClientRequestFilter`s, `MessageBodyWriter`s, `WriterInterceptor`s, etc.) may be executed on either thread."_

The wording is a bit cumbersome but if I understand it correctly the test should not expect a `ClientRequestFilter` to be executed using the thread that invoked the asynchronous method. As a result, if `TLAddPathClientRequestFilter` is invoked on a different thread the `TLAsyncInvocationInterceptorFactory.tlInt` thread local does not contain the correct value.

See also https://github.com/eclipse/microprofile-rest-client/blob/master/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/providers/TLAddPathClientRequestFilter.java#L33

**Comment by andymc12** [comment]
Hi @mkouba - sorry for the slow reply.  The wording in the spec is intended to indicate that providers on the outbound chain can be executed on either thread (the thread calling the client interface method _or_ the async thread).  

Different implementations have differing views on how async methods should handle providers on the outbound flow.  CXF executes those providers on the calling thread, while RestEasy executes them on the async thread.  The wording in the spec and the TCK tests are intended to ensure that both approaches work.

I have tested this in CXF and it passes.  Are you seeing failures with a different implementation?  If so, we may need to investigate further to determine if there is a bug in the test or the implementation.

Thanks for raising this issue.

**Comment by mkouba** [comment]
Hi @andymc12, so I went through the test once again and now I understand that `TLAsyncInvocationInterceptorFactory.tlInt` threadLocal is set by `TLAsyncInvocationInterceptorFactory` on the calling thread and by `TLAsyncInvocationInterceptor` on the async thread. In other words, the test _is correct_ because it doesn't really matter on which thread the `TLAddPathClientRequestFilter` is invoked.

I think it wouldn't hurt to add some more notes on how the test is supposed to work in this regard ;-)

I'm closing the issue. Thanks for your input!
