### ISSUE TITLE
TCK expects MP Config settings applied to non-CDI defined interfaces

### ISSUE THREAD

**Issue by michalszynkiewicz** [eclipse/microprofile-rest-client#142]
`TimeoutViaMPConfigTest` expects `connectTimeout` and `readTimeout` from MP Config settings to set the appropriate timeouts on a client that is created with `RestClientBuilder`, and, if I understand correctly, to take precedence over the builder setting.

While it may be reasonable to let users override what they set programmatically with configuration properties, the spec says "For CDI defined interfaces, it is possible to use MicroProfile Config properties to define...", and doesn't seem to mention that these properties should also work with a programmatically configured client.

@andymc12 am I missing something? If it's a bug in the TCK, I can try to create a PR to fix it.

https://github.com/eclipse/microprofile-rest-client/blob/450f6d5c01fe8f3b21eaf223be713b118b4f5427/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/TimeoutTestBase.java#L52-L67

and:
https://github.com/eclipse/microprofile-rest-client/blob/450f6d5c01fe8f3b21eaf223be713b118b4f5427/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/TimeoutViaMPConfigTest.java#L34-L52

**Comment by kenfinnigan** [comment]
+1 to amending spec text

**Comment by michalszynkiewicz** [comment]
In this case, will we also allow to override providers, base uris, etc for programmatically created clients?

**Comment by michalszynkiewicz** [comment]
I asked the question because, from the user perspective, it would be confusing for me if some properties were applied while the other were not.
After some thought I'm tending to think I'd rather have the programmatically generated clients not impacted by the MP Config settings.
E.g. similarly to the example of using the same client with different URIs, I think someone might want to have a different timeout for clients generated from the same interface.

Programmatically creating the client, one can define their own MP Config properties and use them to build the client.

**Comment by kenfinnigan** [comment]
I'd almost also lean towards programmatic operation not being impacted at all by MP config settings.

That's most likely the "power user" type of situation where they want full control over everything, so I think it makes sense

**Comment by michalszynkiewicz** [comment]
@andymc12 will do!
I'm also thinking of adding a test that would check if the config values don't impact programmatically create clients, WDYT?

**Comment by andymc12** [comment]
Thanks, yes, I think that is a good idea.
