### ISSUE TITLE
Q: How generic types (e.g. List<MyPojo>) are handled?

### ISSUE THREAD

**Issue by progaddict** [eclipse/microprofile-rest-client#157]
related to the bug: https://github.com/OpenLiberty/guide-microprofile-rest-client/issues/67

I'm curious and would like to know how do you handle generics?

A REST client is generated at runtime (by the `RestClientBuilder`) and therefore there is no type information due to the type erasure mechanism. So how do you map an HTTP response body to a `List<MyPojo>` ?

Since `javac` has erased all types in generics, the `RestClientBuilder` sees only `List<Object>` which introduces a mapping problem... Am I missing something ? Is some metadata stored somewhere which can be used to restore the type information?

**Comment by andymc12** [comment]
Hi @progaddict - sorry for the slow response.  Generics in the MP Rest Client should be handled similarly to entities returned in JAX-RS.  Depending on the media type used, this may require the use of a custom `MessageBodyReader` or `MessageBodyWriter`.  In your example, it appears that you are using application/json, and Open Liberty should support generics via JSON-B - I'm planning to fi that as a bug in Liberty, but if you were using a different media type that the MP Rest Client or JAX-RS spec does not require to be "built-in", then you would need to create and register an appropriate MBR and/or MBW.

Hope this helps!

**Comment by progaddict** [comment]
Hi @andymc12 

Nevertheless, thank you for your response.

I'd like to expand my question a little bit because I still do not understand how the bug is going to be fixed.

Suppose, we have the following interface:
```java
@Path("my-service")
public interface MyService {
    @GET
    @Path("{type}/my-pojos/{date}")
    List<MyPojo> getMyPreciousPojos(
            @PathParam("type") final String pojoType,
            @PathParam("date") final String date
    );
}
```

And suppose we would like to construct an HTTP client and call the remote service having this interface:
```java
final MyService client = RestClientBuilder.newBuilder()
        .baseUrl(new URL("https://foo.bar/1.0/"))
        .build(MyService.class);
final List<MyPojo> myPojos = client.getMyPreciousPojos("FOOBARBAZ", "20190205");
```

The construction of the client happens at **runtime**, doesn't it?
It means that the `javac` has already erased types.
Therefore the `RestClientBuilder` at the moment when it constructs an HTTP client (i.e. **at runtime**) will see the following interface:
```java
@Path("my-service")
public interface MyService {
    @GET
    @Path("{type}/my-pojos/{date}")
    List<Object> getMyPreciousPojos(
            @PathParam("type") final String pojoType,
            @PathParam("date") final String date
    );
}
```

:question: So my question was how the `RestClientBuilder` is going to infer the actual type (i.e. `MyPojo`) when it has already been erased by the `javac` :question:

The [JSON-B's documentation](http://json-b.net/users-guide.html#mapping-a-generic-collection) gives the following example:
```java
// List of dogs
List<Dog> dogs = new ArrayList<>();
dogs.add(falco);
dogs.add(cassidy);
// Create Jsonb and serialize
Jsonb jsonb = JsonbBuilder.create();
String result = jsonb.toJson(dogs);
// Deserialize back
dogs = jsonb.fromJson(result, new ArrayList<Dog>(){}.getClass().getGenericSuperclass());
```
where the anonymous class `new ArrayList<Dog>(){}` is used to capture the type of items.
However, this anonymous class is written at **compile time** and therefore the trick with type capture works.

:question: The question is how do you do the same trick **at runtime** :question:

Maybe I am missing something... But as far as I know, the erased type information cannot be restored via reflection at runtime unless you have some sort of metadata (e.g. some annotations with type hints):
```java
@Path("my-service")
public interface MyService {
    @GET
    @Path("{type}/my-pojos/{date}")
    @ReturnsListOf(MyPojo.class)
    List<MyPojo> getMyPreciousPojos(
            @PathParam("type") final String pojoType,
            @PathParam("date") final String date
    );
}
```
where `ReturnsListOf` is a runtime-retained annotation:
```java
@Inherited
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface ReturnsListOf {
    Class<?> value();
}
```
in this case you can retrieve the metadata at runtime and determine that the returned type is the `value` property of the attached annotation.

**Comment by progaddict** [comment]
Try to run the following code snippet:
```java
package com.foo.bar;

import java.lang.reflect.Method;
import java.util.List;

public class Baz {

    public static void main(final String[] args) {
        final Method[] methods = MyService.class.getMethods();
        for (final Method m : methods) {
            System.out.println(m.getName());
            System.out.println(m.getReturnType());
            System.out.println(m.getReturnType().getGenericSuperclass());
        }
    }

    public interface MyService {
        List<MyPojo> getMyPreciousPojos(final String pojoType, final String date);
    }

    public static class MyPojo {
        private String name;
        private String value;

        public String getName() {
            return name;
        }

        public MyPojo setName(final String name) {
            this.name = name;
            return this;
        }

        public String getValue() {
            return value;
        }

        public MyPojo setValue(final String value) {
            this.value = value;
            return this;
        }
    }
}
```
I see the following output:
```
getMyPreciousPojos
interface java.util.List
null
```
The last `null` corresponds to the `m.getReturnType().getGenericSuperclass()`

**Comment by progaddict** [comment]
as an alternative to using annotations for providing metadata (e.g. `@ReturnsListOf`) one could theoretically intercept the `javac` and emit either metadata or some code (e.g. anonymous classes capturing type information) into the final JAR / WAR / *.class files.

this trick with intercepting `javac` is used e.g in the [Lombok](https://projectlombok.org/) project where setters and getters are generated "on the fly" during compilation.

this is of course rather a complex solution. black magic of 80 lvl :smiley:

**Comment by andymc12** [comment]
Hi @progaddict - the generic info is erased at runtime, but there is still metadata in the class files that allows reflection to determine the generic type.  The [ParameterizedType](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/ParameterizedType.html) interface provides this information.

If I modify your example to add a couple lines, like so:
```
...
        for (final Method m : methods) {
            System.out.println(m.getName());
            System.out.println(m.getReturnType());
            System.out.println(m.getReturnType().getGenericSuperclass());
            System.out.println(m.getGenericReturnType());
            System.out.println( ((java.lang.reflect.ParameterizedType)m.getGenericReturnType()).getActualTypeArguments()[0] );
        }
...
```

Then I get the following output:
```
getMyPreciousPojos
interface java.util.List
null
java.util.List<Baz$MyPojo>
class Baz$MyPojo
```

I've tested my fix locally with JSON-B and it works.  Fortunately JSON-B has API methods that take `Type` parameters which allow us to pass in `ParameterizedType` instances - and JSON-B can convert the JSON text (String or InputStream) into a parameterized object.

Hope this helps!

**Comment by progaddict** [comment]
hi @andymc12 

thanks a lot for the helpful explanation :+1: 
now I got it that the generic types can be handled at runtime and it's just the question of integrating `RestClientBuilder` with the JSON-B API.
I'm looking forward to the fix :smiley:
