### ISSUE TITLE
TestMessageBodyWriter does not override the default body writer in Jersey

### ISSUE THREAD

**Issue by urbim** [eclipse/microprofile-rest-client#165]
Hi!

I'm having another issue implementing the specification with Jersey.

The problem seems to be in the sort order in which the body writers are considered in Jersey. Jersey first checks the MediaType of the declared provider and only then proceeds to check if the provider is custom (non-internal, see: [WorkerComparator](https://github.com/eclipse-ee4j/jersey/blob/4ae3004dc2ffb9f44aceb6853661c3ed741650ac/core-common/src/main/java/org/glassfish/jersey/message/internal/MessageBodyFactory.java#L327)). This causes the [TestMessageBodyWriter](https://github.com/eclipse/microprofile-rest-client/blob/master/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/providers/TestMessageBodyWriter.java) to be ignored in some tests (the Jersey internal body writer is used instead).

If I annotate the TestMessageBodyWriter with `@Produces(MediaType.TEXT_PLAIN)` everything seems to be working as expected.

Again, I'm not sure if that is the expected behaviour of the JAX-RS implementation, so I'm asking here first. I can submit the PR with annotated TestMessageBodyWriter if you wish.

**Comment by andymc12** [comment]
Hi @urbim, I believe that the current test is correct, based on text in the JAX-RS 2.1 spec and the MP Rest Client 1.2 spec.

From section 4.2.3 of the JAX-RS spec:
```
Message body readers and writers MAY restrict the media types they support using the @Consumes 
and @Produces annotations respectively. The absence of these annotations is equivalent to their 
inclusion with media type (“*/*”), i.e. absence implies that any media type is supported. An 
implementation MUST NOT use an entity provider for a media type that is not supported by that 
provider.
```

so, no annotation means that it could be considered for any content-type. 

Also, both JAX-RS and MP Rest Client state that user-specified providers should be preferred to the out-of-the-box providers - for example, JAX-RS section 4.1.3 states:
```
Application-supplied providers enable developers to extend and customize the JAX-RS runtime. 
Therefore, an application-supplied provider MUST always be preferred over a pre-packaged one if a 
single one is required.
```

And the MP Rest Client 1.2 spec (in the [Automatic Provider Registration](
https://download.eclipse.org/microprofile/microprofile-rest-client-1.2.1/microprofile-rest-client-1.2.1.html#_json_p_and_json_b_providers) section) states:
```
Then a JSON-B or JSON-P MessageBodyReader and MessageBodyWriter will be registered 
automatically by the implementation. This is in alignment with the JAX-RS 2.1 specification. The 
provider registered will have a priority of Integer.MAX_VALUE, allowing a user to register a custom 
provider to be used instead.
```

Possibly by explicitly setting the priority of the built-in providers to MAX_VALUE, the user-specified providers would be selected?

Hope this helps,
Andy

**Comment by jansupol** [comment]
I believe the test is really wrong. While the JAX-RS mandates a provider for String and “*/*”, it does not mean the implementation cannot come with a provider for String and "text/plain" as well. The test, however, sends Accept "text/plain", and the provider in the test is not annotated by `@Produces(MediaType.TEXT_PLAIN)`. Any implementation specific String - "text/plain" provider can be used instead of the provider in test.

**Comment by andymc12** [comment]
@jansupol I believe that the intent is that an implementation should only support `"text/plain"` with specific types - see this section in [Default Message Body Readers and Writers](
https://download.eclipse.org/microprofile/microprofile-rest-client-1.2.1/microprofile-rest-client-1.2.1.html#_default_message_body_readers_and_writers):
```
For the following types, and any media type, the runtime must support `MessageBodyReader`s and `MessageBodyWriter`s being automatically registered.

byte[]
String
InputStream
Reader
File

Values supported with text/plain
The following types are supported for automatic conversion, only when the media type is text/plain.

Number
Character and char
Long and long
Integer and int
Double and double
Float and float
Boolean and boolean (literal value of true and false only)
```

I believe that the intent of this section was that implementations were to provide MBRs/MBWs that support `byte[], String, InputStream, Reader, and File with */*` and `Number, Character/char, Long/long, Integer/int, Double/double, Float/float, Boolean/boolean with text/plain` - and not more specific media types for the first group.  

Still, it doesn't explicitly say that implementations must not provide a built-in MBR/MBW of `String with text/plain`, so we could change the test to add `@Consumes("text/plain") / @Produces("text/plain")` to the `TestMessageBodyWriter` class.  Can you propose a PR?

Thanks, Andy

**Comment by urbim** [comment]
Thanks both for the explanations. I can create a PR if you wish.
