### ISSUE TITLE
Improved baseUrl configuration

### ISSUE THREAD

**Issue by markusincognitus** [eclipse/microprofile-rest-client#168]
Hello,

the current way of configuring baseUrls for endpoints is impractical for real-world microservice scenarios.
It's necessary to configure a baseUrl for each single endpoint. If you have a system with >100 endpoint interfaces and >10 Microservices/APIs then you would have to configure the baseUrl for more than 100 endpoints ...

A better solution would be to group endpoints (e.g. to APIs or Microservices) and configure only one baseUrl for them.

Example:
Microservice1 uses 30 endpoint interfaces of Microservice3, Microservice8 and Microservice10 then it should be possible to configure something like microservice3.baseUrl, microservice8.baseUrl and microservice10.baseUrl.

Currently even workarounds/hacks are difficult because the MicroProfile Config interface "ConfigSource" doesn't support dynamic property names and so it's not possible to implement the grouping in custom ConfigSource ...

Maybe I've overseen some hidden feature but this topic could be adressed somehow better in the specs.

BR Markus

**Comment by andymc12** [comment]
Hi @markusincognitus - Thanks for bringing up this issue.  I believe that this is one of the scenarios @kenfinnigan had in mind when he opened issue #115.  We certainly could solve the problem using config keys.  

One possible approach would be to put a new `configKey` attribute in the `@RegisterRestClient` annotation.  That would allow multiple client interfaces to be configured by the same set of MP Config properties - for example:
```
@RegisterRestClient(configKey="host1")
public interface Client1 { ... }

@RegisterRestClient(configKey="host1")
public interface Client2 { ... }

@RegisterRestClient(configKey="host1")
public interface Client3 { ... }
```
Then, users could set the base URI for all three interfaces with this config property:
`host1/mp-rest/uri=http://localhost:9080/endpoint1`

The same would also apply to other config settings (like provider registration, timeouts, etc.).

The plan is for config keys to go into the 1.3 release (it was a stretch goal for 1.2, but we ran out of time).

Thanks again, Andy

**Comment by markusincognitus** [comment]
Hello,

this sounds like a great solution.
I'm looking forward to version 1.3 :-)

BR Markus
