### ISSUE TITLE
RestClient usage feedback and problems

### ISSUE THREAD

**Issue by ivanjunckes** [eclipse/microprofile-rest-client#170]
Hey guys, I have been using the rest client for awhile. And I would like to give a feedback as a user on the experience I had.

If we have 2 apps:
movies-app (jax-rs resources, rest clients, model etc)
cinema-app (uses the rest client)

To be able to use the rest client I need to have movies-app packaged in 2 ways:
movies-app.war (with the app resources)
movies-app-client.jar (with the app client and model classes used in the client)

There are issues with this:
1 - I need to use different maven plugins to do this
2 - This plugins need to exclude or include classes using a pattern
3 - If I try to add the movies-app-client in eclipse using classifier it doesn't recognizes it correctly if the movies-app.war is in the same workspace, it actually the whole movie-app project in the classpath
4 - All of this needs to be figured out by the user which makes the experience very bad

If we decide to create the rest client in the cinema-app we will need the model to be exported in a jar so the client app can use it. (I don't like this solution as well)

I may be missing something, but has somebody gone through the same issues?

A possible solution for this would be to have a maven plugin to export a jar with the rest client dependencies. What do you think?

**Comment by markusincognitus** [comment]
Hello,

I think the best would be to create 3 maven projects (movies-app, movies-api and movies-client) where movies-app and movies-client have a dependency on movies-api which contains the interfaces/model classes.
Eclipse is doing very will in automatically resolving your maven dependencies within workspace and automatically setting up classpath, ...
There is no need for excluding/including any classes via maven plugins.

BR Markus

**Comment by ivanjunckes** [comment]
In my opinion we shouldn't mandate that the project uses the module and packaging formatting you are suggesting. People may use different structures like:

- package by domain
- package by layer

We can't really tell them what the project structure should be. In my project for example we use package by domain.

**Comment by kenfinnigan** [comment]
There are two ways to solve the problem, and it's all about preference;

1. Package the API/Model classes in a common JAR that can be used by client and server
2. Duplicate the API/Model classes across the client and server.

There are various pro's and con's to each approach, it all depends on your preference as to whether client and server are intrinsically tied together (1) or if you prefer a bit more separation (2).

I don't think providing tooling for particular usages is something that the spec should define

**Comment by Emily-Jiang** [comment]
We discussed at today's spec call and based on the above conversations, this issue is not directly related to the spec. Close this for now. Please reopen if you think otherwise.
