### ISSUE TITLE
Docker/Kubernetes-compatible config keys

### ISSUE THREAD

**Issue by markusincognitus** [eclipse/microprofile-rest-client#171]
Hello,

in "cloud-native" environments often Docker/Kubernetes is used and configuration is done via environment variables (e.g. via YAML resource definition files).

The MP Rest Client currently uses config keys which are not compatible with this setup because they can't be configured as env variables.

Example error message from Kubernetes:
The Deployment "example-service" is invalid: 
* spec.template.spec.containers[0].env[0].name: Invalid value: "com.example.ExampleResource/mp-rest/url": a valid environment variable name must consist of alphabetic characters, digits, '_', '-', or '.', and must not start with a digit (e.g. 'my.env-name',  or 'MY_ENV.NAME',  or 'MyEnvName1', regex used for validation is '[-._a-zA-Z][-._a-zA-Z0-9]*')

Compatible alternatives to "com.example.ExampleResource/mp-rest/url":
- mp-rest.url_com.example.ExampleResource
- com.example.ExampleResource_mp-rest.url
- com.example.ExampleResource.mp-rest.url

BR Markus

**Comment by kenfinnigan** [comment]
This is definitely a problem, and I've raised it at the MP Config spec level as I think we need to ban the use of '/' in a key

**Comment by jmesnil** [comment]
@kenfinnigan MP Config already provides a solution for this use case: 
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#default-configsources

You can use the env var `com_example_ExampleResource_mp_rest_url` (or `COM_EXAMPLE_EXAMPLERESOURCE_MP_REST_URL`) to configure it.

**Comment by kenfinnigan** [comment]
@jmesnil ok, but isn't it just easier to ban use of '/' in a key so there's no confusion about what the key is for a given environment?

**Comment by jmesnil** [comment]
@kenfinnigan MP Config should not ban use of `/` because some of its config source (and in practice we are only talking about env vars) do not allow it.

Users of MP Config (such as the REST client) can enforce that convention in their own codebase but that's not something to mandate from MP Config.

**Comment by kenfinnigan** [comment]
You mean some config sources don't allow '/'?

Why not? Surely there's lots of confusion if you need to use different key names in different environments. Isn't it simpler if they're all the same?

**Comment by jmesnil** [comment]
> You mean some config sources don't allow '/'?

Env var do not allow it.

Nothing prevents you (microprofile-rest-client) to use the same key name across all possible config source. In that case, you have to chose a naming convention that is accepted across all of them. But that's not up to the MP Config to enforce this.
In other words, the microprofile-rest-client can ban the use of `/` in its key but the MP config will not enforce it.

**Comment by kenfinnigan** [comment]
I guess that's my point.

Why shouldn't we consider MP Config to enforce it to simplify usage for developers?

**Comment by jmesnil** [comment]
MP Config simplifies usage for developers as it lets them define the config names.
It also made sure that there was mapping rules in place for the case where properties would be configured in the environment variable.

**Comment by markusincognitus** [comment]
The automatic replacement of non-alphanumeric characters with '_' is a solution for the problem.
However it's a non-intuitive hidden feature and should be made more visible :-)

BR Markus

**Comment by andymc12** [comment]
So, iiuc, it sounds like we have a couple options here:
1) We could update the spec with a note indicating that users might need to set the environment variables using underscores instead of slashes and dashes (i.e.  `COM.EXAMPLE.EXAMPLECLIENT_MP_REST_URI=http://somehost/...`), or
2) We could deprecate the existing property names, and replace them with ones that use dots and underscores (i.e. client implementations would look for `com.example.ExampleClient_mp_rest_uri` instead of `com.example.ExampleClient/mp-rest/uri`).

Of the two, I tend to favor (1) since it involves no changes to existing user applications, but I'm not seriously opposed to (2).  Or maybe there is another option?

**Comment by jmesnil** [comment]
> We could deprecate the existing property names, and replace them with ones that use dots and underscores (i.e. client implementations would look for com.example.ExampleClient_mp_rest_uri instead of com.example.ExampleClient/mp-rest/uri).

Note that dot (`.`) might also not be allowed in env var either (at least for most unix shell)

**Comment by cescoffier** [comment]
@jmesnil You are right, `.` is not allowed:

```
Environment variable names used by the utilities in the Shell and Utilities volume of
POSIX.1-20xx consist solely of uppercase letters, digits, and the ’_’ (underscore). 
```

**Comment by Emily-Jiang** [comment]
Andy, I suggest you mention: for setting the properties as environment variables, please refer to MP Config for naming conventions in section x.

**Comment by kenfinnigan** [comment]
I think we need to confine the discussion to one thread, so let's keep it on MP Config for now

**Comment by brunobat** [comment]
Hi folks, Any idea if this will move forward?

**Comment by andymc12** [comment]
Hi @brunobat - if I understand the outcome of MP Config issue https://github.com/eclipse/microprofile-config/issues/420, it sounds like the merged solution is better documentation that environment variables should use underscores to replace all non-alphanumeric characters in the config property.

Further, there were some guidelines at the MP umbrella spec level to indicate that slashes should be used in config properties as separator characters.  IIUC, MP Rest Client is following recommended practices for config names.

Unless there is any strong disagreement, I think we can close this issue without any further action.
