### ISSUE TITLE
Spec should not mandate separate thread for async handling

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-rest-client#186]
Currently the specification and TCK require async handling to be performed on a separate thread.

With reactive it's highly likely that asynchronous handling of the response will be done on the same thread, but after the initial request method has completed.

This will require changes to the spec and TCKs. I have an idea on how the TCKs could be modified to verify this, but would like other thoughts. My current thought is to use a `ClientResponseFilter` to interrogate the stack of the Thread to ensure that the test method that triggered the invocation is not in the call stack handling the response.

From some quick printing of stack traces I think it will work, but would appreciate @cescoffier and others verifying that I'm not mistaken about how the asynchronous response would be handled.

**Comment by cescoffier** [comment]
> With reactive it's highly likely that asynchronous handling of the response will be done on the same thread, but after the initial request method has completed.

It depends on the reactive model, but yes, in the reactive world you cannot be sure on which thread you are going to run.

I believe that the underlying HTTP client should use the thread it controls to execute the request, as there is a good chance it contains (for non-reactive HTTP client) a thread pool.  For reactive / non-blocking HTTP client, that's also up to the underlying technology to decide how this need to be handled. 

If the user wants to be executed on a specific thread/thread pool, he can switch thread using one of the `async` methods of the `CompletionStage` API and pass the corresponding `Executor`.
