### ISSUE TITLE
Update to SSL tests using client authentication

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-rest-client#194]
We need to add `sslContextFactory.setEndpointIdentificationAlgorithm(null);` to `HttpsServer.trustStore(...)`.  This is required to avoid a broken pipe exception in Jetty - documented in Jetty issues [3656](https://github.com/eclipse/jetty.project/issues/3656) and [3454](https://github.com/eclipse/jetty.project/issues/3454).

This change should go into `master` and `1.3.X-service` branches.  Until then, implementors would need to use a version of Jetty prior to `9.4.18.v20190429` when running the TCK.

**Comment by kenfinnigan** [comment]
Isn't that adding workarounds for Jetty into MP REST?

**Comment by andymc12** [comment]
Not really.  The Jetty folks will not be changing this behavior, so we'll either need to use the `sslContextFactory.setEndpointIdentificationAlgorithm(null);` approach or we'll need to use `SslContextFactory.Server` as the server implementation - I think this is the preferred approach, but that implementation only exists in Jetty version `9.4.18.v20190429` and higher.

Neither approach is ideal, but setting the endpoint id algorithm to null seems to be forward and backwards compatible.

**Comment by jclingan** [comment]
Merged in 2019. Time to close this issue.
