### ISSUE TITLE
AsyncMethodTest#testAsyncInvocationInterceptorProvider is racey

### ISSUE THREAD

**Issue by stuartwdouglas** [eclipse/microprofile-rest-client#203]
org.eclipse.microprofile.rest.client.tck.providers.TLAsyncInvocationInterceptor#removeContext happens after the CompletionStage in the test is complete. This means there is no guarentee the test will actually see this method as being run, as it may not have happened yet.

**Comment by reta** [comment]
Hey @stuartwdouglas, we've been seeing the same issue with CXF's MP Client implementation when running the TCK. I am wondering what MP Client implementation you are running TCK against? Thank you.

**Comment by stuartwdouglas** [comment]
Quarkus, so a modified version of the Smallrye implementation.

**Comment by dmatej** [comment]
Unfortunately I can see it failing again now with GlassFish 7.0.25 and 7.1.0-SNAPSHOT. It doesn't fail always, but on my laptop in some 2/3 executions.
```
AsyncMethodTest>Arquillian.run:137->testAsyncInvocationInterceptorProvider:242 expected [808] but found [0]
```
```
        <dependency>
            <groupId>org.eclipse.microprofile.rest.client</groupId>
            <artifactId>microprofile-rest-client-tck</artifactId>
            <version>3.0.1</version>
            <scope>test</scope>
        </dependency>

```

**Comment by Emily-Jiang** [comment]
@jamezp @jim-krueger can you take a look at this?

**Comment by dmatej** [comment]
We updated to 4.0, the test fails in around 50% of executions on my machine.

**Comment by jamezp** [comment]
A challenge seems reasonable to accept here. I can see it looks fragile. Sorry this took so long to look at.
