### ISSUE TITLE
Create separate API/SPI components

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-rest-client#21]
Create separate API and SPI.  The current `RestClientBuilder` represents an API that end users interact with.  Create a new SPI that implementers will satisfy that can be used in OSGi and non-OSGi aware environments.

Below is an agreed upon list of changes:
- Create a new `RestClientBuilderProvider` abstract class in a new `spi` package:
  - It should have the logic of doing the `ServiceLoader` based look up
  - Exposes static method that creates a builder
  - Have a static method that sets the provider
  - Have an instance level method to create a builder
  - The static method for creating a new builder should load the service if not already loaded, and call the instance method on that loaded service.  If set provider was called, it should use that instance instead of a SerivceLoader look up.
- Migrate `RestClientBuilder` to be an interface
  - It has a static method that just delegates down to the SPI to avoid end users calling the SPI

**Comment by andymc12** [comment]
I prefer `newBuilder` because it is consistent with the JAX-RS Client API.  It also indicates that the returned builder will be a new instance.  I don't know how MP Config's builder works, but usually when I think of `instance()`, I think it returns the same instance each time it is called.  For MP Rest Client, I think we want a new instance for each call.

**Comment by kenfinnigan** [comment]
+1 to `newBuilder`

**Comment by johnament** [comment]
It was agreed in a prior call that we would keep `newBuilder` since it aligns better with the JAX-RS client API.  Likewise in MP Config, we use `Config.getConfig()` not `Config.instance()`

**Comment by Emily-Jiang** [comment]
In the ConfigProviderResolver, we have instance() not newResolver() and then it has getBuilder()

**Comment by Emily-Jiang** [comment]
Please refer to the config and health apis. The pattern is: Provider/Resolver, Builder and final object. There should be a method to set Provider/Resolver for OSGi environment. I suggest to create a Resolver class, you can discover the builder and then say newBuilder() and setBuilder() for OSGi environment.

**Comment by johnament** [comment]
Discussed on a call today, we're going to create a new class `RestClientBuilderProvider` which will handle the state of the builder provider and manage OSGi requirements.  Convert `RestClientBuilder` into an interface with a static method for create a newBuilder to avoid end users needing to deal with the SPI.
