### ISSUE TITLE
Is it possible to change PropertyNamingStrategy?

### ISSUE THREAD

**Issue by mxmind** [eclipse/microprofile-rest-client#211]
Just wondering how can I change the PropertyNamingStrategy for JSONB used in rest-client, without touching it on the resource layer.
We need to integrate the big 3-rd party layer where the LOWER_CASE_WITH_UNDERSCORES named strategy used.
I'll appreciate any help.

**Comment by andymc12** [comment]
Hi @mxmind - I don't think there are any easy answers that is defined by the spec (other than annotating all of your entity fields with `@JsonbProperty("name_with_underscores")`.

That said, the implementation that you use may support using a `ContextResolver<Jsonb>`.  That allows you to create your own `Jsonb` instance using JsonbConfig with your desired naming strategy.  I know that Open Liberty's implementation supports this, and I believe that Jersey may also support it (they definitely do on the JAX-RS server side, but I haven't tested it on the MP Rest Client).  Other implementations may also have this support.

Basically, the way it works is that you would register a provider like the following:
```
public class MyJsonbContextResolver implements ContextResolver<Jsonb> {
    @Override
    public Jsonb getContext(Class<?> type) {
        JsonbConfig config = new JsonbConfig().
                withPropertyNamingStrategy(LOWER_CASE_WITH_UNDERSCORES);
        return JsonbBuilder.newBuilder().
                withConfig(config).
                build();
    }
}
```

I'd give that a try to see if that works.  If it doesn't it might be worth requesting that feature from your vendor.  If you are ok with this, I would like to change this issue to add `ContextResolver<Jsonb>` support to the MP Rest Client spec in a future release, as I think it would be a good feature to have in all implementations for portability.

Hope this helps!
