### ISSUE TITLE
AbstractSslTest does not pass information on the classpath

### ISSUE THREAD

**Issue by pdudits** [eclipse/microprofile-rest-client#218]
AbstractSslTest passes keystore location via `WebArchive.addAsManifestResource`
https://github.com/eclipse/microprofile-rest-client/blob/1f7cb8a2ffb804c6f3709c52fe3dd5cd7af644f5/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/ssl/AbstractSslTest.java#L98
Expecting it to be read from the classpath in `initializeSslLocations`
https://github.com/eclipse/microprofile-rest-client/blob/1f7cb8a2ffb804c6f3709c52fe3dd5cd7af644f5/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/ssl/AbstractSslTest.java#L102

If TCK is not run in embedded mode, where static fields are already initialized, the tests fail with `NullPointerException` in
```
java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at org.eclipse.microprofile.rest.client.tck.ssl.AbstractSslTest.getKeyStore(AbstractSslTest.java:74)
	at org.eclipse.microprofile.rest.client.tck.ssl.SslContextTest.shouldSucceedMutualSslWithValidSslContext(SslContextTest.java:51)
```

`WebArchive.addAsManifestResource` in fact does not put the resource on the classpath, rather to `/META-INF/` directory in the root of the war file. [SHRINKWRAP-266](https://issues.jboss.org/browse/SHRINKWRAP-266) discusses this, concluding that it is correct, but utterly useless behavior.

**Comment by kenfinnigan** [comment]
Merged
