### ISSUE TITLE
SimpleFeature shouldn't have @Provider on it

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-rest-client#225]
[SimpleFeature](https://github.com/eclipse/microprofile-rest-client/blob/master/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/providers/SimpleFeature.java) currently has `@Provider` present on it which results in it being auto-discovered in the CDI injection test.

Depending on the order the tests are executed this can lead to issues whereby the RestClientBuilder believes the provider is already registered.

It's safer to not have the `@Provider` annotation and just register it manually.

**Comment by andymc12** [comment]
@kenfinnigan Good catch.  Should we also remove the `@Provider` annotation from `InjectedSimpleFeature`?  IIUC, the annotation is also unnecessary because the `FeatureProviderClient` interface has this annotation: `@RegisterProvider(InjectedSimpleFeature.class)`

wdyt?

**Comment by kenfinnigan** [comment]
would you like that in these PRs too?

**Comment by andymc12** [comment]
Yeah, that would probably be simplest.  If you'd rather do them in separate PRs though, that's fine too.  Thanks for catching this.

**Comment by kenfinnigan** [comment]
@andymc12 I've updated both PRs
