### ISSUE TITLE
Registering providers via both builder and annotation

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-rest-client#25]
There exists an ambiguity in the spec, on what happens when providers are registered via both builder and via annotation.

It was agreed at a high level we need to consider:
- Allowing builder to override interface (builder removes providers declared by interface)
- Allowing interface to override builder (interface removes providers declared by builder)
- Do we allow both of these or only one?
- How do we aggregate and order the set of providers?

**Comment by kenfinnigan** [comment]
Allowing one or the other to override sounds like a recipe for problems.

Could we not just have a priority on the provider registration, and when two providers (one builder and one on interface) have the same priority that the interface wins as the application developer should have the final say about what provider is present?

**Comment by johnament** [comment]
At face value, I can agree with you.  However, its quite in line with how JAX-RS works already.  The various register methods define the priority to use for various providers so I would consider this more specifying how those methods work.

Take a look at [Configurable.register(Object,Map)](https://docs.oracle.com/javaee/7/api/javax/ws/rs/core/Configurable.html#register-java.lang.Object-java.util.Map-) for instance.

**Comment by johnament** [comment]
- `@RegisteredProvider(value=Class, priority=-1)`, as a new annotation to register a provider with an overridden priority
- `-1` will have special meaning to indicate that the value is not set.
- Clarify that the behavior is ascending with priority (to align with JAX-RS)
- Allow the builder to override the annotated values, using the various `register` methods defined in `Configurable`
- Add TCK tests that show the changing of priority via the builder

**Comment by johnament** [comment]
```java
@Provider
@Priority(100)
public class MyMessageBodyReader ... {
}

@RegisteredProvider(value = MyMessageBodyReader.class)
public interface MyInterface { }
// this uses the reader's priority
```
```
// show how it works for interface
//RestClientBuilder.newBuilder().register(MyMessageBodyReader.class, 300);
```
