### ISSUE TITLE
Review comments on Rest Client 1.3-RC2

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-rest-client#253]
In the spec, it states:

> If a client interface specifies a custom `ClientHeadersFactory` via the `@RegisterClientHeaders` annotation, and if CDI    manages a valid instance of that class, then the implementation must use that instance, allowing support of `@Inject`   injection into the instance.

The above sentence is unclear. How do I know whether CDI manages a valid instance. If it is CDI managed instance, surely it supports `@Inject`. Therefore, "allowing" does not make sense.

I think it is much better to rephrase to be:
If a client interface specifies an implementation `ClientHeadersFactory` via the `@RegisterClientHeaders` annotation, and if that implementation is a CDI bean, then the Rest Client implementation must use the instance managed by CDI, which enables the support of `@Inject`.

Another minor comments on the [javadoc](https://download.eclipse.org/microprofile/microprofile-rest-client-1.4-RC2/apidocs/org/eclipse/microprofile/rest/client/ext/ClientHeadersFactory.html), 

> If the ClientHeadersFactory instance is invoked while in the context of a JAX-RS request, the implementation must support injection of fields and method annotated with @Context.

I would change method to `methods` to read better with fields.

**Comment by jclingan** [comment]
Closed. 1.3 has been released eons ago. Re-open if still an issue.
