### ISSUE TITLE
Be API for Java SE

### ISSUE THREAD

**Issue by gergelymolnarpro** [eclipse/microprofile-rest-client#254]
Can it be a simple Java SE API or is it? I show you a example: CDI 2.0 now a simple API and it has implementations, those do not require servlet container.

**Comment by andymc12** [comment]
@gergelymolnarpro Yes, the MP Rest Client _can_ run in a Java SE environment (with or without CDI).  Implementations are not required to run in Java SE - but most implementations do.  I think that CXF, Jersey and RestEasy all run in Java SE.

Hope this helps!

**Comment by gergelymolnarpro** [comment]
Are the server and a client able to use same interface? (Example: separated Api with interfaces is created for both communication)

**Comment by andymc12** [comment]
Yes, it is possible.  That said, I don't think that the JAX-RS spec requires server-side implementations to support annotations on interfaces.  So if you want your app to be portable, you might have to duplicate some annotations - for example:

Client:
```
@Path("/widget")
@Produces("application/json")
@Consumes("application/json")
@RegisterRestClient
public interface WidgetService {

    @GET
    @Path("/{widgetId}")
    public Widget getWidget(@PathParam("widgetId") String id);

    // ...
}
```

Server:
```
@Path("/widget")
@Produces("application/json")
@Consumes("application/json")
public class WidgetServiceImpl implements WidgetService {

    @GET
    @Path("/{widgetId}")
    public Widget getWidget(@PathParam("widgetId") String id) {
        return dataStore.getWidgetById(id);
    }

    // ...
}
```

Because of the duplication required for portability, I think many Rest Client users shy away from using the interface in both places, but I know there are still many of them who do.

**Comment by gergelymolnarpro** [comment]
Thanks!

**Comment by gergelymolnarpro** [comment]
> Yes, it is possible. That said, I don't think that the JAX-RS spec requires server-side implementations to support annotations on interfaces. So if you want your app to be portable, you might have to duplicate some annotations - for example:
> 
> Client:
> 
> ```
> @Path("/widget")
> @Produces("application/json")
> @Consumes("application/json")
> @RegisterRestClient
> public interface WidgetService {
> 
>     @GET
>     @Path("/{widgetId}")
>     public Widget getWidget(@PathParam("widgetId") String id);
> 
>     // ...
> }
> ```
> 
> Server:
> 
> ```
> @Path("/widget")
> @Produces("application/json")
> @Consumes("application/json")
> public class WidgetServiceImpl implements WidgetService {
> 
>     @GET
>     @Path("/{widgetId}")
>     public Widget getWidget(@PathParam("widgetId") String id) {
>         return dataStore.getWidgetById(id);
>     }
> 
>     // ...
> }
> ```
> 
> Because of the duplication required for portability, I think many Rest Client users shy away from using the interface in both places, but I know there are still many of them who do.

Good news: no need to duplicate annotations:
https://github.com/eclipse-ee4j/jaxrs-api/issues/847#issuecomment-588627564

**Comment by rdebusscher** [comment]
Correct, annotations on interfaces are supported. But only on **methods**, not on the interface definition itself.

So with the example given above,

> @Path("/widget")
> @Produces("application/json")
> @Consumes("application/json")
> public interface WidgetService

Path, Produces and Consumes are ignored by JAX-RS (or implementation doesn't need to have support for this)
