### ISSUE TITLE
Adapter and inheritance

### ISSUE THREAD

**Issue by gergelymolnarpro** [eclipse/microprofile-rest-client#255]
Does the rest client support to use adapter for convert special formated json into object?
Does the rest client support inheritance from super interface (interface extends interface)?
Is it support Json-B?

**Comment by andymc12** [comment]
> Does the rest client support to use adapter for convert special formated json into object?

Yes, by default, MP Rest Client supports JSON-B.  That allows a user to create an interface method like:
```
@GET
@Produces("application/json")
MyObject getMyObject();

@POST
@Consumes("application/json")
void postMyObject(MyObject myObject);
```

Then the built-in JSON-B Provider should convert MyObject to JSON in the GET request and JSON to MyObject in the POST request.

> Does the rest client support inheritance from super interface (interface extends interface)?

Yes.  An Rest Client interface can be a sub-interface and the methods on the super-interface will also work as Rest Client method.

> Is it support Json-B?

Yes, but I believe that the support is only required if the vendor implementation you are using supports JSON-B.
