### ISSUE TITLE
Enable CDI integration for client filters added via RegisterProviders

### ISSUE THREAD

**Issue by irishshagua** [eclipse/microprofile-rest-client#256]
I ran into a problem when trying to configure a rest client provider different in test and prod code. Because the `@RegisterProvider` annotation relies on an empty constructor to create, it is not possible to parameterize the filter via CDI. This meant I had to switch to manually creating the rest client via a builder. If the provider wiring was CDI aware, this would give a lot more flexibility as to how people could get live/test changes etc...

i.e. something like below could make test wiring a lot easier:
```
@Path("/api")
@RegisterRestClient
@RegisterProvider(MyRequestFilter::class.java)
interface ApiClient {

    @PUT
    @Path("/resource/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    Resource upsert(Resource body, @PathParam("id") Integer id)
}

@Singleton
public class MyRequestFilter implements ClientRequestFilter {

    @Inject
    public ApiKeyResolver apiKeyResolver;

    override public void filter(ClientRequestContext requestContext) {
        requestContext.headers.add("SomeApiKey", apiKeyResolver.resolve());
    }
}

// Live Code
@Singleton
public class KeyVaultApiKeyResolver implements ApiKeyResolver {

    override public String resolve() {
        // Do some awkward prod lookup here
    }
}

// Test Code
@Alternative
@Priority(1)
@Singleton
public class DummyApiKeyResolver implements ApiKeyResolver {

    override public String resolve() {
        return "abc123"
    }
}
```

**Comment by andymc12** [comment]
I think this makes a lot of sense - and it is consistent with what we did in version 1.4 with the `ClientHeadersFactory` - basically making it CDI-aware.  I'll target this for the 2.0 release.
