### ISSUE TITLE
@RestClient - the current @Target is wrong

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-rest-client#257]
The current value is `@Target({ElementType.CONSTRUCTOR, ElementType.FIELD, ElementType.METHOD})`.

1. It's not possible to inject a rest client into a method or a constructor parameter (missing `ElementType.PARAMETER`).
2. It's not possible to define test mocks for rest client interfaces (missing `ElementType.TYPE`).

CDI qualifiers typically define the target as follows: `@Target({METHOD, FIELD, PARAMETER, TYPE})`. `ElementType.CONSTRUCTOR` is completely useless.

**Comment by mkouba** [comment]
This issue follows up on https://github.com/eclipse/microprofile-rest-client/issues/232.

**Comment by andreas-eberle** [comment]
@mkouba: I created a PR to add the missing `ElementType.PARAMETER`. Besides that, I was wondering if `ElementType.CONSTRUCTOR` should be in that list.

**Comment by mkouba** [comment]
I believe that the correct value is `@Target({METHOD, FIELD, PARAMETER, TYPE})`, i.e. no `ElementType.CONSTRUCTOR` and add `ElementType.TYPE`.

**Comment by andreas-eberle** [comment]
Why do you think TYPE should be added?

**Comment by mkouba** [comment]
It could be useful when creating mocks:
```java
@Path("/echo")
@RegisterRestClient
public interface EchoClient {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Consumes(MediaType.TEXT_PLAIN)
    String echo(@QueryParam("message") String message);
}

@Priority(1)
@Alternative // Takes precedence over the bean provided by the MP Rest Client impl
@RestClient
class MockEchoClient implements EchoClient {
    public String echo(String message) {
       return "mock!";
   }
}
```

**Comment by andreas-eberle** [comment]
Good idea. I added it to my PR. Thanks for the input!
