### ISSUE TITLE
Disable follow redirect on http client

### ISSUE THREAD

**Issue by kazik666** [eclipse/microprofile-rest-client#268]
Hi,

Is there any option to disable HTTP redirection on underlying HTTP client?

Regards,
Łukasz

**Comment by andymc12** [comment]
I think this makes sense.  I think most implementations already have a property for specifying HTTP redirection, but it might be nice to have a portable property.

For CDI, we could use a boolean MP Config property like:
`com.mycompany.remoteServices.MyServiceClient/mp-rest/followRedirects`

For clients created using the `RestClientBuilder`, we would either need to add a `setFollowRedirects(boolean b)` method or specify a property (for example, `mp.rest.client.followRedirects`) that a user could set with the `RestClientBuilder.property(...)` method.

**Comment by kazik666** [comment]
Andy your proposition is very nice :) I understand that after changes in microprofile implementation it should be also available in Quarkus platform(Of course after changes in dependencies).
