### ISSUE TITLE
Suggestion: A straightforward method to use environment variables to configure API's URI

### ISSUE THREAD

**Issue by ejba** [eclipse/microprofile-rest-client#269]
Usually, I configure API addresses through environment variables. I wished there was a straightforward method to configure those addresses on the interfaces.

E.g.
```Java
@RegisterRestClient(envVar="API_URI")
@Path("/api")
interface ExampleApi {
    @GET
    @Path("/example/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    Example getExample(@PathParam("id") Integer id)
}
```

**Comment by andymc12** [comment]
Hi @ejba - you should be able to set the base URIs using environment variables.  For individual client interface, for example:
```
package my.pkg;

@RegisterRestClient
@Path("/api")
interface ExampleApi {
    @GET
    @Path("/example/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    Example getExample(@PathParam("id") Integer id)
}
```
You would use the MP Config setting of `my.pkg.ExampleApi/mp-rest/uri=http://somehost:9080/someContextRoot`.  MP Config allows you to use the environment variable of `MY_PKG_EXAMPLE_API_MP_REST_URI`.

If you want to configure multiple interfaces with the same base URI, you could use config keys - for example:

```
package my.pkg;

@RegisterRestClient(configKey="rest_client_api")
@Path("/api")
interface ExampleApi {
    @GET
    @Path("/example/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    Example getExample(@PathParam("id") Integer id)
}
```

```
package some.other.pkg;

@RegisterRestClient(configKey="rest_client_api")
@Path("/api2")
interface ExampleApi2 {
    @GET
    @Path("/example2/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    Example2 getExample2(@PathParam("id") Integer id)
}
```

then you could use the environment variable, `REST_CLIENT_API_MP_REST_URI` to set the base URI for both clients.

**Comment by ejba** [comment]
I didn't know that combo! Thanks for the explanation!
