### ISSUE TITLE
implement QueryParamStyle.valueOf()

### ISSUE THREAD

**Issue by rsearls** [eclipse/microprofile-rest-client#280]
When processing MP-Config property "/mp-rest/queryParamStyle" it would be 
helpful to use the property value string to return the QueryParamStyle in
a call to QueryParamStyle.valueOf( value_string) rather than having
to use a switch stmt to check the values.

**Comment by andymc12** [comment]
Hi @rsearls - can you provide some sample code (of the fix and/or of your use case)?  Or if possible, create a pull request with your suggested changes?

**Comment by rsearls** [comment]
User error.  Closing.  Not needed
