### ISSUE TITLE
Feature: build method to pass request header in the RestClientBuilder

### ISSUE THREAD

**Issue by akoserwal** [eclipse/microprofile-rest-client#283]
It would be good to have a builder method to set request header in RestClientBuilder

**Comment by andymc12** [comment]
Hi @akoserwal - thanks for opening this issue.  Can you provide us with a use case?  There are already a few different ways to send request headers (using `@HeaderParam("someHeader")` on a method parameter, using `@ClientHeaderParam(name="someHeader", value="someValue")` on the method or interface, or by implementing a `ClientHeadersFactory` interface) - perhaps one of these approaches might work for you?

**Comment by akoserwal** [comment]
@andymc12: thanks for the suggestions. Here, I need to add a header:
https://github.com/Apicurio/apicurio-registry/blob/master/client/src/main/java/io/apicurio/registry/client/GenericClient.java#L193

I think it would be more convenient to have a builder method where I can provide the header. It will save from the complication of implementing a factory for this basic purpose.

**Comment by akoserwal** [comment]
I have tried using @ClientHeaderParam on a sample application, I don't see any header being sent.

**Comment by hamburml** [comment]
I also need this. The UseCase is the following. I have a mp rest client interface in a library. The user of the library sometimes needs to send header, sometimes he does not. But the user of the library should not add a new interface which extends the interface from the library and adds RegisterClientHeaders Annotation. Instead he uses the RestClientBuilder and adds the header he needs programmatically. This is not possible right now.
