### ISSUE TITLE
[Open Liberty] MicroProfile Rest Client 2.0 Compatible Certification Request

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-rest-client#295]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>

IBM

- [x] Product Name, Version and download URL (if applicable):<br/>

Open Liberty development TCK build - [cl210120201211-1101](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/tck/2020-12-11_1101/openliberty-all-21.0.0.1-cl210120201211-1101.zip)

- [x] Specification Name, Version and download URL:<br/>

[MicroProfile Rest Client 2.0](https://oss.sonatype.org/content/repositories/orgeclipsemicroprofile-1385/org/eclipse/microprofile/rest/client/)

- [x] Public URL of TCK Results Summary:<br/>

https://openliberty.io/certifications/microprofile/restclient/2.0/TCKResults.html

- [x] Java runtime used to run the implementation:<br/>

Java 8 : `java full version "1.8.0_181-b13"`
Java 11 : `openjdk full version "11.0.8+10"`

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>

macOS

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
Very good, @andymc12.  A couple of nits...  I would change the description test for the OL driver to indicate it's a "TCK" build instead of a "nightly" build.  "Nightly" makes it sound like it can be removed at any time and we need these CIs more "permanent".

And, the other thing is to provide a URL for the Spec.  I would point at the eventual maven coordinates for the final 2.0 spec.

And, finally, you need to create and assign a "Certification" label for this repo.  Thanks!

**Comment by dblevins** [comment]
@andymc12 Similar question/comment as @kwsutter.  1) Is this a permanent build that will not be deleted under any circumstances? 2) is there source available for this exact build (a tag or a known hash)?

So you have context on the question, the primary thing we need the compatible implementation for is in the challenge process when someone says part of a TCK is in some way invalid.  In those scenarios, we can use the first compatible implementation as a reference.  It has to be open source so people can see how things were implemented and reproduce the exact build.  A note on that front that a general day range isn't specific enough as a lot of commits can happen in 24 hours.  The source should be the exact source, down to the commit hash or tag, that build the binary.

If any of these are not the case for the compatible implementation, we'd need to discuss.

**Comment by dblevins** [comment]
Easiest answer would be to provide a link to the source that built this binary and that link is specific to the hash or tag.

**Comment by dblevins** [comment]
Another quick question.  What's going to happen to the contents of this page when a new build is available?

 - https://openliberty.io/certifications/microprofile/restclient/2.0/TCKResults.html

If the plan is to keep overwriting it with the latest build data, that's not really in the spirit of public TCK results.   If that's the case, I may suggest something like:

 - https://openliberty.io/<build>/certifications/microprofile/restclient/2.0/TCKResults.html

**Comment by andymc12** [comment]
@kwsutter @dblevins I just updated the initial text to show that it is a TCK build.  It should be permanent.  I also added the download link to the staging repo.

> you need to create and assign a "Certification" label for this repo.

Looks like @Emily-Jiang did that for me.  Thanks Emily!

> 1) Is this a permanent build that will not be deleted under any circumstances?

I can't say under any circumstances, but yes, the intent is that it is a permanent build.  We don't intend to delete it (like we would for normal "nightly" builds).

> 2) is there source available for this exact build (a tag or a known hash)?

Unfortunately, we didn't tag the Open Liberty repo for that build, but I did capture the commit ID ([bc89b8c501c9a2483cf5baef435ff3da144e14e8](https://github.com/OpenLiberty/open-liberty/tree/bc89b8c501c9a2483cf5baef435ff3da144e14e8)).  Will this work?  Otherwise, I can re-certify on a more recent build, but I'd be afraid that that might slow the release.

> Another quick question. What's going to happen to the contents of this page when a new build is available?
> - https://openliberty.io/certifications/microprofile/restclient/2.0/TCKResults.html
>
> If the plan is to keep overwriting it with the latest build data, that's not really in the spirit of public TCK results. If that's the case, I may suggest something like:
> - https://openliberty.io//certifications/microprofile/restclient/2.0/TCKResults.html

The content of the page is controlled by a GitHub repo (https://github.com/OpenLiberty/certifications/blob/prod/microprofile/restclient/2.0/TCKResults.adoc). The nice thing about that is that the history will be preserved.  Unless directed by somebody like Kevin or Emily, I don't plan to change it.  That said, it might make sense to update it once an official release of Open Liberty is certified as passing the TCK, but as you mention we could do it in a separate document.

Hope this helps!

**Comment by kwsutter** [comment]
> The content of the page is controlled by a GitHub repo (https://github.com/OpenLiberty/certifications/blob/prod/microprofile/restclient/2.0/TCKResults.adoc). The nice thing about that is that the history will be preserved. Unless directed by somebody like Kevin or Emily, I don't plan to change it. That said, it might make sense to update it once an official release of Open Liberty is certified as passing the TCK, but as you mention we could do it in a separate document.

@andymc12 You should have separate TCK Results pages for each time that you submit results.  So, if at a later time, you were going to submit updated results for RestClient 2.0 (like for a final Open Liberty build), then I would suggest creating a new page.  Maybe calling it TCKResults-OL21.0.0.3.html, or something like that.  Leaving it as TCKResults for now is fine, but don't plan to override this in the future.

**Comment by kwsutter** [comment]
> > 1. is there source available for this exact build (a tag or a known hash)?
> 
> Unfortunately, we didn't tag the Open Liberty repo for that build, but I did capture the commit ID ([bc89b8c501c9a2483cf5baef435ff3da144e14e8](https://github.com/OpenLiberty/open-liberty/tree/bc89b8c501c9a2483cf5baef435ff3da144e14e8)). Will this work? Otherwise, I can re-certify on a more recent build, but I'd be afraid that that might slow the release.

@andymc12 We're having a similar discussion with @njr-11 in his Context Propagation CCR.  The binary used as the compatible implementation has to be reproducible and permanent.  As @dblevins pointed out, this record may be referenced many moons from now to verify the correctness of the Specification, API, TCK, and CI.  We need something that will stick around and could be re-built, if necessary.
