### ISSUE TITLE
Test testServerClosesConnection is possibly incorrect

### ISSUE THREAD

**Issue by Verdent** [eclipse/microprofile-rest-client#302]
Hi,
I think that this [test](https://github.com/eclipse/microprofile-rest-client/blob/c5ef4de9f675c2d02be91219899d6571b70f3e3a/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/sse/BasicReactiveStreamsTest.java#L191) might be incorrect. I was adding support for SSE events and I got problems with SSE client auto-reconnect feature. It was basically constantly reconnecting and every time it got the whole batch of the data. Firstly I thought it is a problem of the client, but then I found this "Clients will reconnect if the connection is closed; a client can be told to stop reconnecting using the HTTP 204 No Content response code." written [here](https://html.spec.whatwg.org/multipage/server-sent-events.html). 

Did I get something wrong or is the test really incorrect?

**Comment by jamezp** [comment]
The TCK challenge, #1007, was rejected. We will close this issue based on the feedback in that issue.
