### ISSUE TITLE
Restclient 1.4 spec external url is broken

### ISSUE THREAD

**Issue by nssachin** [eclipse/microprofile-rest-client#307]
Hi,
Microprofile Rest client 1.4.0 release external URL is broken and it takes to `404` page.
### Steps:

1. Select MicroProfile Version `MP 3.3`
2. Click on TypeSafe Rest Client external url which takes to `https://github.com/eclipse/microprofile-rest-client/releases/tag/1.4.0` and throws `404`

The release tag version seems to be configured in `VersionSpecMatrix` class and it seems to be wrongly configured for Rest client `1.4.0` under `MicroProfileVersion.MP33` i.e instead of setting it to `1.4.0` it is set as `1.4` and hence `404` error
```java
 data.put(MicroProfileVersion.MP33,
                new EnumMapBuilder()
                ...
                .add(MicroprofileSpec.REST_CLIENT, "1.4")
```
need to be changed to 
```java
 data.put(MicroProfileVersion.MP33,
                new EnumMapBuilder()
                ...
                .add(MicroprofileSpec.REST_CLIENT, "1.4.0")
```

**Comment by rdebusscher** [comment]
Hi,

Can you create an issue in the MicroProfile Starter project to solve this https://github.com/eclipse/microprofile-starter as this is related to the starter project and not MicroProfile Rest client specification.

Thanks
Rudy
