### ISSUE TITLE
OSGi: does RestClientBuilder (non-CDI) require MP Config at runtime?

### ISSUE THREAD

**Issue by brevilo** [eclipse/microprofile-rest-client#308]
Hi!

I'm trying to integrate a 3rd-party component that uses `RestClientBuilder` [programmatically](https://github.com/ma1uta/jmsdk/blob/master/client-impl/src/main/java/io/github/ma1uta/matrix/client/MatrixClient.java#L146), as far as I can tell. Reading the [spec](https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#mpconfig), I understand that "it is **possible** to use MicroProfile Config", **if** one uses CDI. That should imply that non-CDI implementations shouldn't require MP Config at runtime. However, the OSGi resolver returns this:
```
Unable to resolve org.eclipse.microprofile.rest.client/2.0.0: missing requirement [org.eclipse.microprofile.rest.client/2.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.eclipse.microprofile.config)(version>=2.0.0)(!(version>=3.0.0)))"
[caused by: Unable to resolve org.eclipse.microprofile.config/2.0.0: missing requirement [org.eclipse.microprofile.config/2.0.0] osgi.serviceloader; osgi.serviceloader=org.eclipse.microprofile.config.spi.ConfigProviderResolver; filter:="(osgi.serviceloader=org.eclipse.microprofile.config.spi.ConfigProviderResolver)"; effective:=active]
```
What am I missing (literally)? Do I have to provide a service implementing the `ConfigProviderResolver` interface, even if `RestClientBuilder` is used only programmatically?

Thanks

**Comment by andymc12** [comment]
Hi @brevilo - yes, the CDI and MP Config dependencies should be considered optional.  This is a bug.  Thanks for reporting it - I'll try to have a fix out shortly.

**Comment by brevilo** [comment]
Sounds great. Thanks for your swift action!

**Comment by brevilo** [comment]
Would be great to see this released when merged 👍

**Comment by brevilo** [comment]
Hi @andymc12, I think I have to reopen this issue,  I'm afraid (let me know if I should move the below to a new one).

`RestClientBuilder` extends `javax.ws.rs.core.Configurable` so it should be perfectly fine to (programmatically) instantiate a new builder and then register various components/providers with it, like so:
```
RestClientBuilder builder = RestClientBuilder.newBuilder()
    .register(myJSONProvider, myPrio);
    .register(new ErrorFilter())
    .register(new LoggingFilter())
    .register(new ContentTypeFilter())
    .baseUrl(myURL);
```

However, [`RestClientBuilder.newBuilder()`](https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/RestClientBuilder.java#L55) calls [`RestClientBuilderResolver.instance()`](https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/spi/RestClientBuilderResolver.java#L68) which eventually calls [`ServiceLoader.load()`](https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/spi/RestClientBuilderResolver.java#L103). Unfortunately, `java.util.ServiceLoader.load()` doesn't work out of the box in an OSGi environment, unless something like [SPI Fly](https://aries.apache.org/modules/spi-fly.html) is used, which doesn't seem to be the case here.

That said, the [comment](https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/spi/RestClientBuilderResolver.java#L67) "method copied and adapted from ConfigProviderResolver in microprofile-config" to me is an indicator that there are still some (CDI-related?) remnants left. Apparently pure programmatical use of `RestClientBuilder` isn't yet possible in an OSGi environment, because of the [hard dependency](https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/spi/RestClientBuilderResolver.java#L83) on the `RestClientBuilderResolver` service that won't be provided when `RestClientBuilder` is used purely programmatically.

Fun fact: the current implementation came about via issue #21 and that explicitly aimed at satisfying OSGi use cases. Go figure... 😏 

So, I might be totally misled here, but so far my assessment sounds somewhat plausible, to me... I think 😉 

Can you shed some light on this?

Cheers

**Comment by andymc12** [comment]
Hi @brevilo - in Open Liberty, we use a mechanism similar to SPI Fly - basically it captures `META-INF/services` files (exposed via Declarative Service) and allows the application's classloader to load them.

However, if you don't have a mechanism like that in place, you can force the SPI resolver to use the implementation of your choosing - you would need to call the `RestClientBuilderResolver`'s [setInstance method](https://github.com/eclipse/microprofile-rest-client/blob/f66e802cecc3cca973ebaa079ea3cc02c845c172/api/src/main/java/org/eclipse/microprofile/rest/client/spi/RestClientBuilderResolver.java#L122) - passing in the resolver of the implementation you are using.  For CXF, that would be `org.apache.cxf.microprofile.spi.CxfRestClientBuilderResolver`.  For other implementations, you should be able to find it by view the `META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver` file that ships with the implementation JARs.  You would need to invoke the `setInstance` method before building any clients - maybe in a bundle activator or DS init method...

HTH!

**Comment by brevilo** [comment]
Hi Andy, thanks (again) for your quick response!

I do in fact use SPI Fly to resolve other `ServiceLoader` uses by the 3rd-party library I need to integrate. However, this only provides the means to resolve the SPI provider/consumer dependencies within an OSGi container - that's not the issue I'm trying to discuss. My question is the following: is the hard dependency on `RestClientBuilderResolver` really a requirement when using `RestClientBuilder` programmatically?

I think it isn't because the [current implementation](https://github.com/ma1uta/jmsdk/blob/master/client-impl/src/main/java/io/github/ma1uta/matrix/client/MatrixClient.java#L146) works just fine (outside OSGi), without implementing any `RestClientBuilderResolver` as far as I can see. Also, let me refer back to the [Rest Client for MicroProfile spec](https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#_sample_builder_usage): the example given there represents the same approach as in the actual codebase referenced. What the spec does not mention is a requirement on a `RestClientBuilderResolver` service 😉 .

Does that make sense?

**Comment by brevilo** [comment]
Hm, maybe I'm confusing API and implementation here...? Duh, the `RestClientBuilder` is just an interface declaration and not an implementation. That would mean I need to find what's implementing this API in my OSGi container, if any 🤔 . Am I right?

**Comment by andymc12** [comment]
Hi @brevilo - looking at the pom.xml in your project, it looks like you are using RESTEasy.  The implementation class for the `RestClientBuilder` API interface is `org.jboss.resteasy.microprofile.client.RestClientBuilderImpl` and the SPI resolver implementation class is `org.jboss.resteasy.microprofile.client.BuilderResolver`.  I haven't worked with the RESTEasy Rest Client implementation in an OSGi environment yet, but I suspect it will work - we have used a forked version of RESTEasy as a JAX-RS implementation in Open Liberty - it uses Equinox, but not Karaf.

If you have some flexibility in Rest Client implementations and you run into problems with RESTEasy (I certainly don't want to dissuade you from using one implementation over another), I know that Apache CXF's implementation is tested in OSGi - it's maven artifacts include OSGi bundles, etc. 

In both cases, you could directly "new up" the `RestClientBuilder` implementation class and use that to build your client instances - the downside to that approach is that it is not portable.  

As for your earlier questions, yes, the `RestClientBuilder` does depend on the `RestClientBuilderResolver` class - per issue #21 that you mentioned.  So the only ways to create a `RestClientBuilder` instance is to use the `ServiceLoader` approach (where the implementation - RESTEasy, CXF, Jersey, etc. - provides the `META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver` file) or to use the `setInstance` method.

If you are pulling RESTEasy into your project, are you creating a bundle manifest for it?  If so, could you add the required `Provide-Capability` and `Require-Capability` [SPI Fly headers](https://aries.apache.org/modules/spi-fly.html#specconf) so that it will expose the service?

HTH

**Comment by brevilo** [comment]
> looking at the pom.xml in your project, it looks like you are using RESTEasy.

First complication: that's not my code, but the library I intend to use. (Also, it uses RESTEasy in the test scope only).

> I know that Apache CXF's implementation is tested in OSGi 

Sounds promising. Already looking into it...

> where the implementation - RESTEasy, CXF, Jersey, etc. - provides the META-INF/services/org.eclipse.microprofile.rest.client.spi.RestClientBuilderResolver file

Hopefully also the SPI Fly capability headers. However, not sure that's enough. The implementation might declare the ServiceLoader Mediator headers but `microprofile-rest-client` does not declare the necessary `Require-Capability` headers, so I don't see how SPI Fly should work.

**Comment by brevilo** [comment]
For the record, in case others run into similar issues: neither do RESTEasy, CXF or Jersey declare the OSGi ServiceLoader Mediator headers (i.e. SPI Fly), nor do they call `setInstance()`. To me that means that "normal" OSGi resolving won't work.

[rant] After 3-4 weeks of hard work to get things _integrated_ (I've written only _*2*_ lines of code myself so far!) I'm almost at the point of giving up. Modularity, loose coupling, so-called standards (like OSGi), abstraction, indirection and dynamic service resolution are all nice concepts, theoretically. Yet it seems that sometimes less would be more 😒 [/rant]

**Comment by andymc12** [comment]
@brevilo I think we could probably add the consumer headers in MP Rest Client, but I don't have a good way to test it.  Would you be up for manually adding the headers to the manifest (might also have to add the producer headers to CXF's manifest) to verify that it works?  I think any "requires" headers should include `resolution:=optional` to avoid adding any hard dependencies.  If that works, you or I could open a new PR here for the MP Rest Client side.  You might have to open an issue with CXF (or RESTEasy/Jersey/etc - but I am only a committer for CXF) to get the producer headers added. Another option might be to add the header(s) in a fragment that attaches to the CXF/RESTEasy/Jersey/etc. bundle.

**Comment by brevilo** [comment]
>  Would you be up for manually adding the headers to the manifest 

Yep, let's try that. I'll add the relevant headers via a `maven-bundle-plugin` build-plugin in the two POMs, ok?
* [cxf-rt-rs-mp-client](https://github.com/apache/cxf/blob/master/rt/rs/microprofile-client/pom.xml)
* [microprofile-rest-client-api](https://github.com/eclipse/microprofile-rest-client/blob/master/api/pom.xml)

>  I think any "requires" headers should include resolution:=optional

Agreed. 

> Another option might be to add the header(s) in a fragment that attaches to the CXF/RESTEasy/Jersey/etc. bundle.

Yikes, no 😉

**Comment by brevilo** [comment]
After a few hours I'm back at square one and history repeats itself: CXF depends on CDI and Microprofile Config.

I'm not able to resolve its dependencies as soon as I add it to my bndtools dev container I'm eventually left with:
```
      ⇒ osgi.identity: (osgi.identity=org.eclipse.microprofile.config)
          ⇒ [org.eclipse.microprofile.config version=2.0.0]
              ⇒ osgi.contract: (&(osgi.contract=JavaCDI)(version=2.0.0))
```
I just can't seem to find any CDI package that provides the JavaCDI contract.

**Comment by andymc12** [comment]
Do you need MP Config?  If not, then you should be able to make those imports optional in the CXF bundle.  They probably should be already... that's something I can fix too, but can you confirm that it works if you make those changes?

**Comment by brevilo** [comment]
First of all: thanks for your patience Andy! I really appreciate it! 👌 

I marked the MP Config and CDI dependencies as optional in `cxf-rt-rs-mp-client`'s POM and could **finally** resolve CXF in bnd/Equinox (after dealing with dual chain issues of course)!

I also had to remove the `Bundle-ActivationPolicy := Lazy` header from said bundle's manifest because it would otherwise remain in `STARTING`, despite the enabled ServiceLoader Mediator (SPI Fly). To me that's a bug in OSGi, or at least a not-fully-thought-through spec/implementation.

Anyhow, CFX's `RestClientBuilderResolver` service is now found and loaded by the MP Rest Client - yeah! 🍻 

Unfortunately, CFX throws an exception as soon as `RestClientBuilder.build()` is called on `CxfTypeSafeClientBuilder`:
```
org.apache.cxf.bus.extension.ExtensionException: Could not create object of extension class org.apache.cxf.bus.osgi.OSGIBusListener.
	at org.apache.cxf.bus.extension.Extension.load(Extension.java:234) ~[?:?]
	at org.apache.cxf.bus.extension.ExtensionManagerImpl.loadAndRegister(ExtensionManagerImpl.java:198) ~[?:?]
	at org.apache.cxf.bus.extension.ExtensionManagerImpl.initialize(ExtensionManagerImpl.java:116) ~[?:?]
	at org.apache.cxf.bus.extension.ExtensionManagerBus.doInitializeInternal(ExtensionManagerBus.java:260) ~[?:?]
	at org.apache.cxf.bus.extension.ExtensionManagerBus.initialize(ExtensionManagerBus.java:250) ~[?:?]
	at org.apache.cxf.bus.CXFBusFactory.createBus(CXFBusFactory.java:43) ~[?:?]
	at org.apache.cxf.bus.CXFBusFactory.createBus(CXFBusFactory.java:36) ~[?:?]
	at org.apache.cxf.bus.CXFBusFactory.createBus(CXFBusFactory.java:32) ~[?:?]
	at org.apache.cxf.BusFactory.getDefaultBus(BusFactory.java:107) ~[?:?]
	at org.apache.cxf.BusFactory.createThreadBus(BusFactory.java:243) ~[?:?]
	at org.apache.cxf.BusFactory.getThreadDefaultBus(BusFactory.java:227) ~[?:?]
	at org.apache.cxf.BusFactory.getThreadDefaultBus(BusFactory.java:214) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSServiceFactoryBean.getBus(JAXRSServiceFactoryBean.java:69) ~[?:?]
	at org.apache.cxf.microprofile.client.MicroProfileServiceFactoryBean.createResourceInfo(MicroProfileServiceFactoryBean.java:34) ~[?:?]
	at org.apache.cxf.jaxrs.JAXRSServiceFactoryBean.setResourceClass(JAXRSServiceFactoryBean.java:148) ~[?:?]
	at org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean.setServiceClass(JAXRSClientFactoryBean.java:171) ~[?:?]
	at org.apache.cxf.microprofile.client.MicroProfileClientFactoryBean.<init>(MicroProfileClientFactoryBean.java:69) ~[?:?]
	at org.apache.cxf.microprofile.client.CxfTypeSafeClientBuilder.build(CxfTypeSafeClientBuilder.java:147) ~[?:?]
        [...]
Caused by: java.lang.ClassCastException: Cannot cast org.apache.cxf.bus.managers.CXFBusLifeCycleManager to org.apache.cxf.buslifecycle.BusLifeCycleManager
	at java.lang.Class.cast(Class.java:3605) ~[?:?]
	at org.apache.cxf.bus.extension.ExtensionManagerImpl.getBeanOfType(ExtensionManagerImpl.java:307) ~[?:?]
	at org.apache.cxf.bus.extension.ExtensionManagerBus.getExtension(ExtensionManagerBus.java:181) ~[?:?]
	at org.apache.cxf.bus.osgi.OSGIBusListener.<init>(OSGIBusListener.java:78) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.apache.cxf.bus.extension.Extension.load(Extension.java:222) ~[?:?]
```

I'm going to look into this tomorrow. Smells a bit like another lazy activation issue (e.g. `org.apache.cxf.cxf-rt-rs-extension-providers` is still in `STARTING`), but my brain needs some rest now...

If you have an idea in the meantime, please let me know 🙏 

Cheers

**Comment by brevilo** [comment]
Sorry @andymc12, got side-tracked by other issues. Anyhow, after a short detour with Jersey I did manage to get CXF working with my (limited) OSGi-related modifications discussed above. I'll prepare a few merge requests over at that project. I'm going to mention you (with your CXF committer hat on) and this discussion for reference.

Cheers

**Comment by brevilo** [comment]
Done!

* https://github.com/eclipse/microprofile-rest-client/pull/312
* https://github.com/apache/cxf/pull/805
* https://github.com/apache/cxf/pull/806

**Comment by brevilo** [comment]
Wow! This endeavour took us four months - glad we made it through 😄 

Thanks again for all your support!

**Comment by andymc12** [comment]
You're welcome!  I'm still a little shocked how tricky it was to get done, but glad it's finally working!

**Comment by brevilo** [comment]
Hi @andymc12, what's the current plan for the stable release (e.g. 2.0.1)? It's almost been a year since the last one?

Thanks!

**Comment by brevilo** [comment]
Sorry, I just need to ask this one again:
> Hi @andymc12, what's the current plan for the stable release (e.g. 2.0.1)? It's almost been a year since the last one.
> 
> Thanks!

**Comment by Emily-Jiang** [comment]
@brevilo Rest client 3.0 will be out in a couple of weeks. Would you like to use 3.0 release.

**Comment by brevilo** [comment]
Well, sure. PRs #309 and #312 (see above) were merged in March and May respectively but have been sitting in 2.0.1-SNAPSHOT since then. I'd really like to make use of those in production and thus have been waiting for the next regular release.

Thanks for the update.
