### ISSUE TITLE
throws WebApplicationException, when response is 401

### ISSUE THREAD

**Issue by MarQs1990** [eclipse/microprofile-rest-client#310]
Don't know if this is known and the intended behavior:
As we used the rest client we have seen, that a WebApplicationException is thrown, when the response is of type 401.
When using the rest client I assume, that there is a response returned, no matter what the servers answer is. With the actual behavior you have to catch this exception, to retrieve the 401 information.

**Comment by andymc12** [comment]
Hi @MarQs1990 - thanks for bringing this up!  Let me make sure I understand the concern.

I believe that a server will send a 401 in two cases:
(1) The client has not provided any authentication credentials but is accessing a secured resource. This is basically the server's "challenge" to the client to provide credentials.
(2) The client has provided invalid credentials (i.e. bad password, non-existing username, etc.).

In (2), I think the right response for the Rest Client is to throw a WebApplicationException or some other exception.  It's possible that the client needs to update it's password, or client certificate, etc. and an exception seems like the right way to notify the client.

For (1) though, there might be something that we could add in the spec to handle it.  One option would be to just provide the authentication information on the initial request (Heiko Rupp has a great article on how to do that here: https://itnext.io/authentication-with-microprofile-rest-client-d1e9da774f70 ).  Another option might be to add the concept of an "authenticator" - I believe CXF has an Authenticator class that you could set up to respond to 401s, and other implementations likely have their own (proprietary) authentication callback mechanism.  We could attempt to add something like this to the specification.  Wdyt?

**Comment by svenhaag** [comment]
I think something like this should be thrown: `javax.ws.rs.NotAuthorizedException`

**Comment by andymc12** [comment]
> I think something like this should be thrown: javax.ws.rs.NotAuthorizedException

@svenhaag that sounds like a great idea to me. I think that the default response exception mapper should handle that.

**Comment by svenhaag** [comment]
Can we make this part of the TCK?

**Comment by andymc12** [comment]
> Can we make this part of the TCK?

For sure. Would you be interested in crafting the changes?  If not, I can try to get to it next week.  Thanks!

**Comment by Emily-Jiang** [comment]
Close this one based on the discussion on #345. Please reopen if you think this is different from that one.
