### ISSUE TITLE
Have string overloaded methods for uri/url methods

### ISSUE THREAD

**Issue by maxandersen** [eclipse/microprofile-rest-client#334]
i.e. `.baseUri("https://restcountries.eu/rest")` should be sufficient not require to always type `.baseUri(URI.create("https://restcountries.eu/rest"))`

**Comment by Emily-Jiang** [comment]
This involves API, Spec and TCKs updates. @whitecat22 will work on this.

**Comment by WhiteCat22** [comment]
I will take this issue.

**Comment by WhiteCat22** [comment]
https://github.com/eclipse/microprofile-rest-client/pull/372
