### ISSUE TITLE
Allow ResponseExceptionMapper to swallow exceptions

### ISSUE THREAD

**Issue by RDM-FODMOB** [eclipse/microprofile-rest-client#338]
For certain outgoing calls, I would like to be able to swallow 404s and have those methods return `null` instead of having them throw an exception. With the current specification, a `ResponseExceptionMapper<T>` can not swallow exceptions because only implementations returning null (from `toThrowable`) are considered to have not handled the response:

> The first one discovered where toThrowable returns a non-null Throwable that can be thrown given the client method’s signature will be thrown by the runtime.

Practically, if I want to swallow 404s in my project, I would need to disable the default response exception mapper (since it handles 404s) yet reimplement it just to be able to have the default behavior for certain endpoints, and reimplement it a second time with special treatment of 404s for those other endpoints.

I don't really understand why it is built this way, shouldn't the decision to handle a response be the responsibility of the `handles` method alone?

**Comment by andymc12** [comment]
I can provide a little bit of the history here.  When we were initially discussing the `ResponseExceptionMapper` design, we came to an impasse around the `handles` method - some of us wanted the signature to include the whole `Response` object while others of us wanted to only provide the user with the status code and headers to ensure that the method exited quickly (i.e. preventing the user from reading the entity stream or other expensive operations). The compromise was that we could have better performance by keeping the `handles` method limited but if a more thorough check was necessary (like reading the entity stream) that the user could do that in the `toThrowable` method - i.e. if the entity contains some value, return an exception, but if not, then return null and perhaps another `ResponseExceptionMapper` could handle the response.

So, if we want to add a return-null option, I think what we'd need is a designated exception (e.g. `org.eclipse.microprofile.rest.client.ReturnNullException`) that users' `ResponseExceptionMapper` could return.  Any of the other options that I could think of would end up breaking existing behavior.

**Comment by RDM-FODMOB** [comment]
I see. A special type of exception would work in a non-breaking way and would totally be acceptable, though it would feel a bit weird... how about supporting a return type of `Optional<T>` with the implied semantics that 404s return an empty optional?

**Comment by RDM-FODMOB** [comment]
@andymc12 based on your feedback I've reconsidered my current approach by defining a custom (checked) exception and a response exception mapper specifically for it. Now I can keep the default response exception mapper and deal with 404s by declaring and catching my custom exception (rather than catching web application exception and swallowing/rethrowing based on the status). It's already much cleaner in my opinion, making me doubt if there is a need for a swallow mechanic after all... I'm OK to have this closed unless you'd consider adding this feature anyway.

**Comment by andymc12** [comment]
Cool, I'm glad that works. I'll go ahead and close this issue - but I'm definitely willing to consider changing this approach to allow the client interface to return null - or better handle `Optionals`, etc.  If you (or anyone else) would like to see this functionality added, please re-open.  Thanks!
