### ISSUE TITLE
MicroProfile Rest Client 3.0 release on Maven Central?

### ISSUE THREAD

**Issue by brevilo** [eclipse/microprofile-rest-client#342]
Hi @andymc12, 

you released 3.0 eleven days ago, marking the first stable release in a year. Yeah! What's the ETA to have it available at [Maven Central](https://search.maven.org/search?q=g:org.eclipse.microprofile.rest.client)? I'd really like to see it updated downstream as well, i.e. in Apache CXF, but I reckon Maven Central availability is a minimum prerequisite for that.

Thanks!

**Comment by andymc12** [comment]
Hi @brevilo - I haven't used that site before, but the 3.0 release should be in Maven Central - see:
https://mvnrepository.com/artifact/org.eclipse.microprofile.rest.client/microprofile-rest-client-api/3.0 and
https://repo1.maven.org/maven2/org/eclipse/microprofile/rest/client/microprofile-rest-client-api/3.0/

Maybe the index hasn't been updated yet...

I can't speak for Apache CXF, but I believe that they are planning to upgrade to the Jakarta package space soon - in which case, they would need to pull in the 3.0 release.  

Thanks!

**Comment by brevilo** [comment]
> Maybe the index hasn't been updated yet...

You're right indeed. The [3.0 release](https://search.maven.org/artifact/org.eclipse.microprofile.rest.client/microprofile-rest-client-api/3.0/jar) is available, but the index didn't catch it. In my experience this happens (at most) 24 hours after deployment so it seems that this isn't a temporary index problem.

Well, let's hope it gets fixed with the next point release which is hopefully not taking another year 😏 

Thanks!
