### ISSUE TITLE
Setting SSLContext for CDI injected clients

### ISSUE THREAD

**Issue by Baddy247** [eclipse/microprofile-rest-client#344]
Hi,

I have a CDI injected rest client using `@RegisterRestClient`. I am planning to implement mutual auth/2-way auth for this client and I was wondering how to initialize the `SSLContext` object. From the documentation I only see it is possible for `RestClientBuilder`. I'd appreciate any help.

**Comment by AhmedEzzat12** [comment]
Thanks @andymc12 that did work!

**Comment by Emily-Jiang** [comment]
Based on the above comments, we are going to close this as there are no better solution than what @andymc12 recommended.
