### ISSUE TITLE
Replace javax namespace usage with jakarta

### ISSUE THREAD

**Issue by jeanouii** [eclipse/microprofile-rest-client#346]
Latest MicroProfile release relies on the new Jakarta namespace.

I still found some remaining javax.* imports not being replaced. We should remove all Maven dependencies to javax libraries and also update sources to use jakarta namespace instead.

This is causing issue when trying to run TCK because it's using javax.servlet imports.

**Comment by andymc12** [comment]
Hi @jeanouii - can you describe the issues you are seeing?

We discussed the javax.servlet imports in two different issues - see this comment (https://github.com/eclipse/microprofile-rest-client/issues/316#issuecomment-937545565) and subsequent discussion as well as issue #341 (which describes how Open Liberty / Wildfly addresses this problem).

The TL;DR is that MP Rest Client 3.0 uses WireMock/Jetty which does not support the jakarta namespace on JDK 8, but MP Rest Client 3.0/ MP 5.0 must support JDK 8.  So for this release at least, the javax.servlet imports are required - unless WireMock/Jetty backports their changes. HTH.
