### ISSUE TITLE
[question] Can I build a new implementation for microprofile-rest-client?

### ISSUE THREAD

**Issue by ljtfreitas** [eclipse/microprofile-rest-client#349]
Hi :wave: ,

I've built a pet project named [julian-http-client](https://github.com/ljtfreitas/julian-http-client) for my needs and for the company that I work for, and I'm thinking about implement this specification.

So, do I just have to read the spec, write the required features, run the TCK tests and after pass, submit the results? Is there some restriction for a single developer implement that?

Thank you so much :slightly_smiling_face:

**Comment by otaviojava** [comment]
@ljtfreitas, how are you?

Yeap, it is an excellent first step.

There is no restriction.

If you have any questions, please, let us know.

@Emily-Jiang, did I forget anything?

**Comment by Emily-Jiang** [comment]
@otaviojava was correct! Feel free to implement the spec! We also welcome your feedback and your contribution @ljtfreitas ! Please feel free to raise issues  if you have any questions.

**Comment by ljtfreitas** [comment]
Nice. Thank you so much @otaviojava @Emily-Jiang :hugs:
