### ISSUE TITLE
ClientRequestFilter and ClientResponseFilter priority tests absent from MP Rest Client TCK

### ISSUE THREAD

**Issue by jim-krueger** [eclipse/microprofile-rest-client#358]
Implementations of `jakarta.ws.rs.client.ClientRequestFilter`  and `jakarta.ws.rs.client.ClientResponseFilter` are required to honor priorities.  
From the javadoc:
`Filters in the filter chain are ordered according to their jakarta.annotation.Priority class-level annotation value.`

Currently there are no TCK tests that verify this.

**Comment by Emily-Jiang** [comment]
@jim-krueger will work on this.
