### ISSUE TITLE
Deployment Exceptions

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-rest-client#36]
Need to handle cases where the application code is in error - these should be documented in the spec and tested in the TCK.  Here are a few of the exceptions we should cover (please add more as we think of them):

* Multiple HTTP method annotations on the same interface method (i.e. `@GET @PUT public Object someMethod()`
* Invalid URI templating (i.e. `@GET @Path("/blah") public Object someMethod(@PathParam("{someParam}")` - in this case there is no path parameter defined
* No `@Path` annotation on the passed-in interface

**Comment by johnament** [comment]
Note - we can only do deployment exceptions for CDI managed clients.  We should define an exception to be thrown when you build a client via the builder as well.

**Comment by andymc12** [comment]
Per discussion yesterday, we decided that we do want to support interfaces without an `@Path` annotation (bullet three above).  That means that we are primarily concerned with the following conditions that would define an invalid interface:
* Multiple HTTP method annotations on the same method
* Invalid URI templating (i.e. PathParams parameters without a valid path template in the URI)

From reading the CDI spec on the different exception types, I think that for the CDI case, these should result in `javax.enterprise.inject.spi.DefinitionException`.  For the case where an invalid interface is passed into the RestClientBuilder's build method, the implementation should throw an IllegalArgumentException.

**Comment by Emily-Jiang** [comment]
I suggest you create a separate exception such as RestClientDefinitionException. For CDI managed beans, this exception will be wrapped under DefinitionException. For builder pattern client, it will be bubbled up without being wrapped or wrapped by JAX-RS.

**Comment by OndrejM** [comment]
I think this is rather a nice-to-have feature than something essential. It shouldn't block releasing 1.0 version. If it doesn't make it into 1.0 it can specified in future versions. I don't see any risk in implementations validating this in different ways or not at all as no business logic should rely on exceptions being triggered.

**Comment by johnament** [comment]
I think the scope covered in the PR is enough.  The big question is whether or not the validations it lists can be covered in an impl.

**Comment by andymc12** [comment]
Another condition we might want to check is when a rest client interface declares a sub-resource locator method that returns a class instead of an interface.
