### ISSUE TITLE
ConfigKeyForMultipleInterfacesTest uses the same WAR file name as ConfigKeyTest

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-rest-client#363]
This is a copy&paste error. The ConfigKeyForMultipleInterfacesTest uses the same name for the WAR file as the ConfigKeyTest test:

https://github.com/eclipse/microprofile-rest-client/blob/a1011eced8f02c25726de04493de22a23ca6d2a0/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/cditests/ConfigKeyForMultipleInterfacesTest.java#L56

It causes issues when we run the TCK against GlassFish: https://github.com/eclipse-ee4j/glassfish/pull/24536#discussion_r1291858086

**Comment by OndroMih** [comment]
@andymc12 , @jamezp , could you please have a look and fix this?

**Comment by jamezp** [comment]
It does look like a copy/paste issue, but I'm not sure I understand why that's causing a problem. I don't have any commit rights to this repository so the best I could do is raise a PR.

**Comment by jamezp** [comment]
TBH I'm not sure when I'd find time either. I've not really done much work on this project and I'm sure anything I might have locally would be out of date.
