### ISSUE TITLE
CDI Interceptor support

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-rest-client#5]
Explain how CDI interceptors are applied.

**Comment by johnament** [comment]
John's specific use case: adding fault tolerance annotations to the interfaces defined by a user.

This can come after 1.0, since you can wrap existing FT annotations in regular CDI beans that delegate to the interface.

**Comment by johnament** [comment]
@NottyCode I almost wonder if we need to get @antoinesd to weigh in on this.  For one, the interface itself is not a CDI bean.  However, are you expecting the fault tolerance annotations to work, even if you manually build the client?

**Comment by pilhuhn** [comment]
See also #107

**Comment by mkouba** [comment]
For the record: this is already implemented in Thorntail/SmallRye. See also http://docs.wildfly-swarm.io/2.1.0.Final/#_cdi_interceptors_support and https://github.com/smallrye/smallrye-rest-client/blob/master/testsuite/basic/src/test/java/io/smallrye/restclient/tests/ft/FaultToleranceTest.java.

**Comment by OndrejM** [comment]
Does it make sense to specify that all annotations on the REST client interface's class or methods, which are also interceptor bindings, are copied to the proxy CDI bean that's injected? This would apply them to the CDI bean and trigger interceptors as if the annotations were added to the virtual CDI bean.

It would be even better if the CDI spec covered this and specified that interceptor bindings are applied also if the annotations are defined on the interface that a CDI bean implements. But until then we can specify it in the MP REST Client spec.

**Comment by mkouba** [comment]
> ...are copied to the proxy CDI bean that's injected?

Hm, what does that mean? There's no _bean class_ for a MP Rest interface so you cannot just "copy" the interceptor bindings.

Also lifecycle interceptors (`@PostConstruct`, etc.) probably do not make much sense here. So we should be clear that only business method interceptors are partially supported (`@AroundInvoke`).

I would use something like:
_If CDI is enabled, it is possible to associate business method interceptors with Rest Client proxy methods by using interceptor bindings._

Plus we should add some warning that the Interceptors spec works with the assumption that a **target class** always exists which is not the case here. So it might happen that some interceptors are not designed to work correctly with MP Rest proxies.

**Comment by andymc12** [comment]
closed with PR #140
