### ISSUE TITLE
How to set read and connect time outs?

### ISSUE THREAD

**Issue by Ravisankar-Challa** [eclipse/microprofile-rest-client#53]

**Comment by andymc12** [comment]
Good question.  In JAX-RS 2.0, read and connect timeouts were set in the Client API using implementation-specific properties - i.e. `ClientBuilder.newBuilder().property("com.ibm.ws.jaxrs.client.connection.timeout", 20000)...`

In JAX-RS 2.1, the expert group added the `connectTimeout` and `readTimeout` to the `ClientBuilder` class to avoid the user needing to use proprietary (non-portable) properties.

MP Rest Client is based on JAX-RS 2.0, so we could allow implementations of the spec to use those same properties from their JAX-RS 2.0 implementation.  Or we could follow suit with JAX-RS 2.1 and add the timeout methods to `RestClientBuilder`.  

Anybody have any strong opinions or alternative options?

**Comment by johnament** [comment]
I would recommend leaving them as implementation specific properties, since we support registering properties.  When we bump to the next version and JAX-RS 2.1 we can align to the methods added in JAX-RS 2.1

**Comment by dansiviter** [comment]
This issue might be mitigated somewhat if there was a way to unwrap an instance of the `javax.ws.rs.client.ClientBuilder` from within the `org.eclipse.microprofile.rest.client.RestClientBuilder`. At the moment some rather untidy reflection is needed to extract and set. SmallRye tries to map ReSTEasy methods to the `#property` method but as the method signature of the timeout methods is a `long` and `TimeUnit` that makes is somewhat more complicated (see [#18](https://github.com/smallrye/smallrye-rest-client/issues/18)).

**Comment by andymc12** [comment]
@dansiviter I was just thinking about coming back to this issue.  

Not all implementations use the `ClientBuilder` as their underlying technology.  I'm not sure about RestEasy, but I know that CXF avoids the ClientBuilder internally, so it would non-trivial to get the ClientBuilder from the generated proxy instance of the Rest Client.

Would it work for you if we added `connectTimeout` and `readTimeout` methods to the `RestClientBuilder` so that it would match JAX-RS 2.1's `ClientBuilder`?

**Comment by dansiviter** [comment]
The concern there is one specific implementation is having a direct impact on specifications for convenience and not for practical reasons. After all, "Rest Client attempts to use JAX-RS 2.0 APIs for consistency and easier re-use." (although in this case it would be JAX-RS 2.1 spec!). Yes, adding `connectTimeout` and `readTimeout` would address my specific use-case, but I'm not convinced it's the right thing to do.
