### ISSUE TITLE
ResponseExceptionMapper.toThrowable() returns null

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-rest-client#71]
I don't understand the motivation to allow for `null` return values on `ResponseExceptionMapper.toThrowable()`. Can some explain the rationale behind this? To me this looks like an invitation to NPE's and it really complicates the ResponseMapper selection, i.e. you might have cases where the priority would determine another mapper, but because this particular one return `null`, you need to fallback to one with higher priority values.

**Comment by andymc12** [comment]
Hi @heiko-braun - the idea for returning `null` is to indicate that this mapper is not applicable.  The `handles` method indicates that, but is intended as a quick check that doesn't need to read entity data, etc.

For a given response, you may have multiple ResponseExceptionMappers (sorted by priority) that returns `true` for the `handles` method.  But on closer look one or more of the mappers may not actually apply, so they should return a null - that tells the implementation to move on to the next potential mapper.  

Hope this helps

**Comment by andymc12** [comment]
@heiko-braun are you ok if we close this issue?  If you have any other questions or concerns, please let me know.  Thanks.

**Comment by andymc12** [comment]
Thanks!
