### ISSUE TITLE
Arguable use of ParamConverterProvider

### ISSUE THREAD

**Issue by heiko-braun** [eclipse/microprofile-rest-client#74]
Some tests (see discussion on https://github.com/eclipse/microprofile-rest-client/pull/69) make use of ParamConverterProvider to change the request parameter values on the client side, prior to the actual HTTP request.

I think using a ParamConverter for these purposes is arguable or even wrong.  The spec only references ParamConverter for injection cases to supply values to resource fields annotated with `@<X>Param`. See section 3.2 in https://github.com/jax-rs/spec/blob/master/spec.pdf.

IMO the following tests make invalid use of a `ParamConverterProvider` and should be changed to not depend on the a `ParamConverter`, which seems to be a server-side extension point only:

- `InvokeWithBuiltProvidersTest` 
-  `InvokeWithRegisteredProvidersTest`
-  `CDIInvokeWithRegisteredProvidersTest` 

@andymc12 Thoughts?

**Comment by andymc12** [comment]
@heiko-braun I agree that it is a little strange expecting a ParamConverter to convert a String to a String.  A better example might be to convert some custom object to String and vice-versa, which I believe is the intent of the ParamConverters.  

I still think it makes sense for ParamConverters to exist on the client side as it facilitates type-safety and better usage of model objects - for example:

```
public interface InventoryService {
    @POST
    @Path("/{widgetId}/{quantity}")
    void order(@PathParam("widgetId") Widget widget, @PathParam("quantity") int qty);

    // vs

    @POST
    @Path("/{widgetId}/{quantity}")
    void order(@PathParam("widgetId") String widgetId, @PathParam("quantity") int qty);
}

... // and

inventory.order(widget, 100);
// vs
inventory.order(widget.getId(), 100); // or some other method to get the id of the widget in question

```

With ParamConverters, users can write the business logic with less code.  What would you think if we changed the ParamConverters and the tests that use them to use custom objects that convert to and from Strings?

**Comment by heiko-braun** [comment]
Thanks @andymc12, I can see the use case. It makes sense when you don't control the Java interface to begin with. I guess I was looking from the angle of creating the interface myself and wondering about the additional complexity. 

The other thing worth mentioning, is the asymmetry. The  `ParamConverter` makes it appear as if the conversion would be happening in both ways, inbound and outbound. But in fact it's really just outbound. On the server-side it's the other way around, but also just in one direction.  But that might be just my RPC wired brain, that took a while to understand what's going on while implementing it.

Feel free to close this one. I think my question have been answered.

**Comment by johnament** [comment]
Do we want to clean up the test to use a more real world example?  Or is it fine as is?

**Comment by andymc12** [comment]
I'm fine with it as it is.  I think there could be valid use cases for String-to-String conversion - like maybe something that does translation.

**Comment by andymc12** [comment]
I think this issue could be dropped from the 1.1 release, but I added the help wanted tag in case somebody has cycles to work on it.  Basically, the change is to make the ParamConverters convert some custom object to a string - rather than a string to a string.  Then the test methods should pass in an instance of that custom object instead of string.
