### ISSUE TITLE
HATEOAS and rest client

### ISSUE THREAD

**Issue by konjp** [eclipse/microprofile-rest-client#89]
Microprofile rest client is still rather new and it is hard to find example for some specific usage, and that is way I'm asking here.
Problem that I now facing is how to use rest client when rest endpoint implements HATEOAS. In this example bellow we have some endpoint `https://localhost1/rest/management` that produces output :
```    
{
    "departmentId": 10,
    "departmentName": "Administration",
    "locationId": 1700,
    "managerId": 200,
    "links": [
        {
            "href": "https://localhost2/rest/employees",
            "rel": "employees",
            "type" : "GET"
        }
    ]
}
```
My question is about how to implement rest client interface that gets content from resource(s) that is defined in `links`.

Do we need to build new client interface(we cannot override base url for client interface already created?) for each link in links? Is building new client interface expensive operation, because we can have a lot of links? 

It would be nice that solution for given problem can be implemented with microprofile rest client CDI support.

Any guidance to existing documentation, example or pointer in direction to solve problem are welcome.

Thanks on your very good work on Microprofile project.

**Comment by andymc12** [comment]
Unfortunately, I don't think MP Rest Client is a good fit for HATEOAS-based services.  If the endpoint URIs remain mostly static (fixed) then you could write your client interface based on the data in the `link` section.

The issue I see with it is the dynamic nature of HATEOAS - I've seen examples where different URIs become available/unavailable based on certain conditions - i.e. a banking service that won't allow you to execute the "withdraw" URI if your account balance is too low.  The MP Rest Client interface would still either have the `withdraw` method or it wouldn't - but the interface methods are fixed (without altering the client side application code).  In a use case like that where certain URIs are unavailable, I would assume that the server would respond with some status code indicating that the URI is invalid (404 or maybe 403, 405, etc.) - in that case the client application could register a `ResponseExceptionMapper` to throw an application-specific exception (i.e. `InsufficientFundsForWithdrawalException`) when that unavailable URI is invoked via the rest client interface.

As far as handling the response data, you could use the built-in JSON-P APIs (JSONObject/JSONArray) as return types - or use return types that are specific to your application, but then you might need to register a `MessageBodyReader` to convert the JSON response into the app-specific object.  In either case, I would probably ignore the `links` section unless you wanted to be aware if the remote service added some new URI(s).

Hope this helps,
Andy

**Comment by derekm** [comment]
RFC says all Links should be in headers, not in documents.

Otherwise HATEOAS links are not URL-rewriting proxy-safe.

If MP Rest Client takes the same headers-only, URL-rewriting-safe Links, it could probably accommodate HATEOAS, as well as demonstrate the correct approach all the people the world over who a "Doing It Wrong™."

**Comment by derekm** [comment]
In other words, MP Rest Client should only support: https://tools.ietf.org/html/rfc5988

As @andymc12 says, Links in content type bodies cannot be supported (and should not be supported, because it is an entirely broken and bad approach).

**Comment by konjp** [comment]
Like in most case when we have problems, they almost always come as chain of events :-). In this particular case we do not have control of rest endpoint and we need information from `links` section, therefore it is not option to ignore links.
We already discussed situation that @andymc12 mentioned. Endpoint is not much dynamic, therefor static (fixed) approach from client side is a option. I know somebody can say then you do not facilities one one major advantage HATEOAS like structure, namely that server can evolve independently from client. But that is out of our control.
Solution that we think to implement to follow links and get content is given bellow like pseudo-code: 
```
foreach link in links and type='GET' do 
RemoteApi remoteApi = RestClientBuilder.newBuilder().baseUrl(link.url).build(RemoteApi.class);
```
@derekm can you little elaborate more on how URL rewrite is done on client side.

Just to add little bit to discussion about linking, a lot of implementations f.e. [HAL](https://tools.ietf.org/html/draft-kelly-json-hal-08), [Siren](https://github.com/kevinswiber/siren) or [Atom](https://tools.ietf.org/html/rfc4287) have linking implemented in content body.

**Comment by t1** [comment]
@konjp The discussion about the pros and cons of HATEOAS are tiresome. They probably can be solved as good as the discussion about tabs and spaces.

But you have a very specific problem at hand that could be solved even with the static nature of the MP Rest Client (if it's not too late): You can simply add a `List<Link> links` field to your `Management` DTO, and the `Link` class would have fields for `href`, `rel`, and `type`. Then you can handle the navigation 'by hand', but it would work.

If that's a good response for you, we could close this issue.

**Comment by svenhaag** [comment]
When using Jackson2 why can we not just utilize: io.openapitools.jackson.dataformat.hal.HALMapper
